### ISSUE TITLE
Bug: program doesn't handle the case where `max_width` and `max_height` are absent

### ISSUE THREAD

**Issue by mahor1221** [jstkdng/ueberzugpp#1]
I installed the [AUR](https://aur.archlinux.org/packages/ueberzugpp) package then I ran `ueberzug layer` command and entered the following input:
```shell
{"action": "add", "x": 0, "y": 0, "path": "/home/mahor/a.jpg"}
```

But I'm not successful displaying the `a.jpg` picture. I'm getting this output:
```shell
{"action":"add","path":"/home/mahor/a.jpg","x":0,"y":0}
terminate called after throwing an instance of 'nlohmann::json_abi_v3_11_2::detail::type_error'
  what():  [json.exception.type_error.302] type must be number, but is null
[1]    185831 IOT instruction (core dumped)  ueberzug layer
```

I tried the same input with `ueberzug` and it worked fine.

**Comment by mahor1221** [comment]
I read the source code and finally, I could display the image with this input: 
```
{"action": "add", "x": 0, "y": 0, "path": "/home/mahor/a.jpg", "max_height":200, "max_width":200 }
```
It seems the program doesn't handle the case where `max_height` and `max_width` are absent.

**Comment by jstkdng** [comment]
adding error checking would reduce speed you know ;P

I guess adding some documentation about the expected json arguments would be helpful.

**Comment by jstkdng** [comment]
The values are not percentages, they represent the number of terminal character boxes.
I only got that from the values that ranger feeds to ueberzugpp. x,y mean the top left corner where to start drawing the image and max_(width,height) mean the maximum amount of terminal characters the image may take, and resizing itself if necessary.

**Comment by tkapias** [comment]
hm, strange, I use TMUX, and for me the x, y, min_width and max_width react like percentage of the screen.

Above 100 I am out of scope. 50 for x or y is in the middle of the screen...

**Comment by jstkdng** [comment]
well, `ueberzugpp` interprets those values are character boxes, not percentages. Must be coincidence that your terminal has ~100 rows

**Comment by tkapias** [comment]
Sorry about that, I got missled because I tried it in a window around 100 width and then in a larger one but there was a typo mistake and it did not work... it's on me.

**Comment by tkapias** [comment]
Then again some infos in the readme would be nice when you have time.

And in the ueberzug fork you mentioned that you want to cover more filetypes, I don't even know what was covered by the original project, you could document that too.

Thanks again.

**Comment by jstkdng** [comment]
yeah, I'll add more documentation once I got time, help is also welcome you know :P

**Comment by tkapias** [comment]
I'm not familiar with C++, so it's difficult to extract a good documentation from the code with my skills.

- I see there seems to be only one parser
- the silent -s option exist and work
- there is no scaler or identifier options

I wanted to help you write more help output. But I don't know how it's built, the silent flag is not in the help currently.

You could add this, probably wrong, text to the Readme:

```markdown
## Usage

The documentation is deferred at this point.

1. The only command currently provided is "layer" to make Ueberzug listen.
  - Layer accepts the silent [-s] option, to hide the textual output of the command.
  
    ```bash
    ueberzug layer -s
    ```

2. You can then feed Ueberzug with json objects to display an image or make it disappear.
  - json object to display the image / replace the image:
  
    ```json
    {"action":"add","max_height":0,"max_width":0,"path":"/path/image.ext","x":0,"y":0}
    ```
  
  The number values are COLUMNS and LINES of your terminal window, in TMUX it's relative to the size of the panels.

  - Don't display the image anymore:
  
    ```json
    {"action":"anything_else"}
    ```

3. This project supports more filetypes by using [opencv](https://docs.opencv.org/4.7.0/d4/da8/group__imgcodecs.html#ga288b8b3da0892bd651fce07b3bbd3a56). But not SVGs, you have to convert and cache them first.

Until further documentation is available, it is easy to find examples of scripts for the Ueberzug using the json parser around the web.

```

**Comment by jstkdng** [comment]
It's fine if you don't know C++, help with documentation is helpful and useful.
