### ISSUE TITLE
zmq.hpp missing?

### ISSUE THREAD

**Issue by sbradnick** [jstkdng/ueberzugpp#10]
I see a `<zmq.hpp>` as an #include in `application.cpp` but don't have that file in a recent clone.

**Comment by jstkdng** [comment]
hey, do you have zeromq installed?

**Comment by sbradnick** [comment]
zeromq-devel-4.3.4-4.1.x86_64 is installed.

**Comment by sbradnick** [comment]
Seems the required package is `cppzmq-devel` (for openSUSE, not sure what it might be elsewhere); using `cmake(cppzmq)` as a BuildRequires gets the job done :+1:

**Comment by jstkdng** [comment]
under arch, the C++ library is in the plain `zeromq` package. I'll update the documentation to specify that.
