### ISSUE TITLE
X11 output method behaves strangely

### ISSUE THREAD

**Issue by sxyazi** [jstkdng/ueberzugpp#101]
The image only shows up when I right click and won't show up in full:

https://github.com/jstkdng/ueberzugpp/assets/17523360/e7646316-0c92-4075-a03c-ae99d5724b8b

```
> echo $TERM
xterm-256color

> echo $XDG_SESSION_TYPE 
x11
```

**Comment by jstkdng** [comment]
could be because max_width and max_height are 0

**Comment by sxyazi** [comment]
Seems not the max_width and max_height reason

https://github.com/jstkdng/ueberzugpp/assets/17523360/6f265a66-c0e7-4cf4-8e1a-4241591bc491

**Comment by jstkdng** [comment]
I just noticed, the image is only showing up on the menu, lmao. Does this happen on other terminals?

**Comment by sxyazi** [comment]
This is the gnome-console, I can't get the gnome-terminal and foot to start properly, probably as of the VM or the architecture, but everything works fine in the Alacritty.

**Comment by jstkdng** [comment]
it seems gnome-terminal and gnome-console don't work that well. I'll document that. Closing then.

**Comment by sxyazi** [comment]
After more extensive testing, I've found that Alacritty occasionally fails to display images directly, requiring me to use the mouse to click once elsewhere in the terminal.


https://github.com/jstkdng/ueberzugpp/assets/17523360/56c6e2d9-916a-4fb8-aab0-afa71beac501

**Comment by jstkdng** [comment]
I also found some issues when using VMs that don't show up on real hardware. Since VMs have not great GPUs.
