### ISSUE TITLE
Unable to work in Hyper

### ISSUE THREAD

**Issue by sxyazi** [jstkdng/ueberzugpp#103]
I was testing Sixel and found that Überzug++ couldn't run in Hyper -- it's a terminal I know of that supports Sixel, and the other one foot couldn't run in my VMs, so I couldn't test it!

The error:

```
❯ ueberzug layer                                          
libc++abi: terminating due to uncaught exception of type std::runtime_error: UNABLE TO CALCULATE TERMINAL SIZES
zsh: abort      ueberzug layer
```

**Comment by jstkdng** [comment]
`ueberzugpp` uses `ioctl` to check terminal sizes, `hyper` probably doesn't return anything when using that system call.

**Comment by sxyazi** [comment]
I try to use `ioctl` in Rust can get the correct value:
```rust
let s = unsafe {
	let s: winsize = std::mem::zeroed();
	ioctl(STDOUT_FILENO, TIOCGWINSZ, &s);
	s
};
dbg!(s.ws_col, s.ws_row, s.ws_xpixel, s.ws_ypixel);
```

<img width="444" alt="image" src="https://github.com/jstkdng/ueberzugpp/assets/17523360/0f5af8c0-b5d2-4f81-af8b-dc1140830f11">

**Comment by sxyazi** [comment]
I'll close the issue and report it to Hyper.

**Comment by jstkdng** [comment]
good luck
