### ISSUE TITLE
How to use the internal cacher for formats which are not images

### ISSUE THREAD

**Issue by mahor1221** [jstkdng/ueberzugpp#107]
Currently, https://github.com/vifm/vifm/pull/927 is my best effort to support other formats with caching, and its performance is incredible, thanks to your efforts and Vifm's plugin system.

However, to achieve this, I had to use `--no-cache` and an external caching system similar to Vimfimg. I couldn't find any other solution. Is there any other way to accomplish this?

**Comment by mahor1221** [comment]
Related?: https://github.com/jstkdng/ueberzugpp/issues/65#issuecomment-1580672137

**Comment by jstkdng** [comment]
`ueberzugpp`'s cache is for caching resized images. `vifm`'s cache saves the image formats as `.jpg` or `.png`.

**Comment by mahor1221** [comment]
So, what do you think I should do to not cripple `ueberzugpp`?

https://github.com/jstkdng/ueberzugpp/issues/105#issuecomment-1663755741: 
> Without the --no-cache option you are crippling ueberzugpp without a reason.

Would you like me to leave this [PR](https://github.com/vifm/vifm/pull/927) unchanged for now? If the caching isn't done correctly, you can always make changes later.

**Comment by jstkdng** [comment]
I'd say remove the `--no-cache` option

**Comment by mahor1221** [comment]
If I remove `--no-cache`, the caching process is have to be done twice and there would be two cached images for every video/audio/pdf/... . It is slightly less performant which is noticeable on my old machine.

**Comment by jstkdng** [comment]
how are the vifm's cached images being saved? do they have an extension?

**Comment by mahor1221** [comment]
> how are the vifm's cached images being saved?

First, a `HASH` is generated using the following command:
```bash
HASH="$(stat --printf "%n%i%F%s%W%Y" -- $FILE_PATH | sha512sum)"
```

Then, we check if an image exists in the `CACHED_IMAGE_PATH`:
```bash
CACHED_IMAGE_PATH="$XDG_CACHE_HOME/ueberzug/$HASH.jpg"
```

If it doesn't exist, the `FILE` is fed into a cacher script, which is usually a single command. For example:
```
ffmpegthumbnailer -i "$FILE_PATH" -o "$CACHED_IMAGE_PATH" -s 720 -q 5
```

Finally, the `CACHED_IMAGE_PATH` is passed to the FIFO of the `ueberzugpp layer --no-cache`.


> do they have an extension?

All of them have the `jpg` extension, and they are guaranteed to be in the JPG format.

**Comment by jstkdng** [comment]
>CACHED_IMAGE_PATH

shouldn't that cache be vifm only?

>First, a HASH is generated using the following command

Why don't you just hash the file path? should be faster

>and they are guaranteed to be in the JPG format

Then that cached image can be used with `ueberzugpp`

It is expected that the first time an image shows up to be slow since it has to be resized to fit the available preview size. And the double caching is only done when you try to preview another type of file. For regular images that can be read by `ueberzugpp` there should be some cache otherwise it will always be slow. I have some 15mb+ pictures that would always take a while to preview if there was no cache.

But yeah, I'd say to remove the `--no-cache` option, it only ever affects the first preview. If it is affecting multiple previews then your caching logic is not working correctly.

**Comment by mahor1221** [comment]
> shouldn't that cache be vifm only?

Yeah, good point. I'll change the path to `$XDG_CACHE_HOME/vifm/`.


> Why don't you just hash the file path? should be faster

It has the advantage that if the file is moved, the same cache can be used.

If the hashing was done completely in C or C++, you would be absolutely right. However, since the plugin is written in Lua and shell commands are being called, I believe the performance is not that different.

![2023-08-06_05-38-07](https://github.com/jstkdng/ueberzugpp/assets/73415437/880386e6-04d4-4770-b2b9-b96930d09a56)
![2023-08-06_05-38-15](https://github.com/jstkdng/ueberzugpp/assets/73415437/36cac9a5-f065-41bb-a384-8d95b01c76bb)

> I have some 15mb+ pictures that would always take a while to preview if there was no cache

Me too, it would be terrible without any cache. Images are also being cached with this command (720 is the maximum width of the cached image):
```
convert -thumbnail 720 "$FILE_PATH" "$CACHED_IMAGE_PATH"
```

> But yeah, I'd say to remove the `--no-cache` option, it only ever affects the first preview. If it is affecting multiple previews then your caching logic is not working correctly.

Rest assured that it only affects the first preview. However, I'm not yet convinced to remove the `--no-cache` option because everything is being cached; it's just being done externally to `ueberzuggg`.

**Comment by mahor1221** [comment]
I propose implementing a feature that allows users to provide scripts for caching images of unsupported file types.

For example:
```bash
ueberzugpp layer --add-thumbnailer="<filetype1>: <script1>" --add-thumbnailer="<filetype2>: <script2>" ...

ueberzugpp layer --add-thumbnailer="video: ffmpegthumbnailer -i '%PATH' -o '%CACHE' -s '%WIDTH' -q 5"
```
In the above command, `ueberzugpp` should replace `%PATH` (required), `%CACHE` (required), and `%WIDTH` (if found) with the correct values.

Here's an example of how it can be used:
```json
{
  "action": "add",
  "identifier": "PREVIEW",
  "x": 0,
  "y": 0,
  "width": 720,
  "height": 360,
  "path": "/path/to/file",
  "filetype": "video"
}
```

**Comment by jstkdng** [comment]
>Images are also being cached with this command (720 is the maximum width of the cached image):

now this is where we should have started, if you are already downscaling the images then caching on `ueberzugpp` is not needed. That being said,  opencv and libvips are faster at downscaling that `imagemagick`. At least caching is being done. Should also help og ueberzug.

>I propose implementing a feature that allows users to provide scripts for caching images of unsupported file types.

Interesting proposal, I'll see what I can do.

**Comment by mahor1221** [comment]
> now this is where we should have started.

Oops 😅, thanks for your time anyway. I've taken the PR on the `vifm` repository out of the draft status.

> That being said, opencv and libvips are faster at downscaling than imagemagick.

I've noticed that `imagemagic` is actually much faster on my machine, it's weird and I don't know why that's the case. Maybe worth investigating.

**Comment by jstkdng** [comment]
>Maybe worth investigating.

haha, you'd need to edit code to benchmark the functions. On my side I found it to be faster. But anyway, good luck with your PR.
