### ISSUE TITLE
Wayfire plugin doesn't place the window according to -x and -y args in ueberzugpp cmd

### ISSUE THREAD

**Issue by Beethoven-n** [jstkdng/ueberzugpp#108]
the image renders to the corner of the window. it does seem to properly parent to the window, but it doesn't seem to go where the -x and -y arguments of the command ask for it to be at the start.
i can't reproduce the bug outside of my joshuto wrapper script because of stoi errors again
```
dogbold@laika:~ % >> ueberzug cmd -s /tmp/ueberzugpp-62810.socket -a add -i "preview" -x="30" -y="30" -f "./pictures/screenshots/2023-08-02_23:45:56.png"
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
```
here's an example of the issue:
![2023-08-02_23:45:56](https://github.com/jstkdng/ueberzugpp/assets/44652883/6e093dd5-1642-47c5-a59a-41314f05768e)

**Comment by jstkdng** [comment]
do you have the ipc and ipc-rules plugin enabled?

**Comment by jstkdng** [comment]
no response from op for some time now, closing.
