### ISSUE TITLE
lf file manager

### ISSUE THREAD

**Issue by se7en-x230** [jstkdng/ueberzugpp#11]
Long term user of
https://github.com/gokcehan/lf/tree/c0c85f206fbd5011c10cc839ced94acb444a1b9a

with 
https://github.com/slavistan/howto-lf-image-previews

any easy way to implement ueberzugpp as a replacement?

**Comment by jstkdng** [comment]
you can try modifying this line: https://github.com/slavistan/howto-lf-image-previews/blob/master/lf-previewer#L7
replace width with max_width and height with max_height.

**Comment by se7en-x230** [comment]
Thanks for the fast reply

After a bit research I found a "saner" way to get all previews in lf with ctpv.
https://github.com/NikitaIvanovV/ctpv

Sadly that does not recognize ueberzugpp at the moment.
I guess this is nothing you can do about on your end.

**Comment by jstkdng** [comment]
seeing their code, they are using some new syntax seebye introduced before killing og ueberzug. I will try to add support for those arguments.

**Comment by jstkdng** [comment]
this should be fixed in release 2.2.1

**Comment by se7en-x230** [comment]
Amazing. Thanks. Works just fine.
