### ISSUE TITLE
Add way to modify the image origin to its center

### ISSUE THREAD

**Issue by diniamo** [jstkdng/ueberzugpp#111]
There is currently not way to have a nice looking fzf preview with ueberzug due not being able to center the image on either axis. The simplest fix is to add a way to modify the image's origin, meaning the position sent to ueberzug is the center of the displayed image. I'm sure fzf previews aren't the only thing that could use this feature.

For our case (lobster's rewrite), the simplest way would be to have a parameter like `--origin center` or something similar, so we don't have to get the image's size either.

**Comment by jstkdng** [comment]
What would be the scope of this feture? centering on just on axis? both?

**Comment by diniamo** [comment]
Well for our use-case, as I said, we want the image's origin to be its center instead of its top-left, maybe it's easier to understand if I put my amazing drawing skills to use:
![ueberzugorigin](https://github.com/jstkdng/ueberzugpp/assets/55629891/82512fd8-9cad-4a76-9b36-3c4fae8b5bc9)
The red points correspond to the points given to ueberzug by the program using it, and the black frame is what ueberzug displays. The top left part is how ueberzug currently works, and top right is how we need it to work.

Not sure what the best way would be to go about this, but potentially an argument accepting the 8 points on the bottom frame? (top left, top center, top right, left center, center, right center, bottom left, bottom center, bottom right)

(Pardon the drawing, I made it on a touchpad)

**Comment by jstkdng** [comment]
Ok, the last thing might not be necessary. Is your rewrite of `lobster` going to support OG ueberzug? Or just `ueberzugpp`.

**Comment by diniamo** [comment]
I'm pretty sure we won't, the original lobster doesn't either. (Just so there is no misunderstanding, the original dev of lobster is still the project owner)

**Comment by justchokingaround** [comment]
we will NOT support the og ueberzug

**Comment by diniamo** [comment]
Huge thanks!

**Comment by diniamo** [comment]
Huge thanks!
