### ISSUE TITLE
Rename `ueberzugpp` to `ueberzug`

### ISSUE THREAD

**Issue by danjenson** [jstkdng/ueberzugpp#117]
I get an error that claims ueberzugpp tmux .... returned error 127, looks like the binary calls `ueberzugpp`, but the build script builds `ueberzug` 

see: https://github.com/jstkdng/ueberzugpp/blob/f9be4b30bae98c3de2c7bad063dc20177bcfa8b4/src/tmux.cpp#L120

solved this with `ln -s ueberzug ueberzugpp` for the time being.

**Comment by jstkdng** [comment]
a symlink is also created when building, so both should coexist.
