### ISSUE TITLE
Screenshots taken in mpv player of videos encoded in h.265 don't render correctly

### ISSUE THREAD

**Issue by jackj1** [jstkdng/ueberzugpp#118]
Here is an example of a screenshot taken in mpv of a h.265 video and how it incorrectly renders in my terminal.

![S04E17-Judgment  7EA91300 :00:00:01 710](https://github.com/jstkdng/ueberzugpp/assets/62434031/6951c9c5-c245-4d2d-aac5-e773fc1a50e4)
![ss-23-08-22_01-17_31](https://github.com/jstkdng/ueberzugpp/assets/62434031/3e355900-2469-4d5c-9ce1-7669ef5244a9)

Probably worth mentioning that every other image I've tested renders correctly, including screenshots taken in mpv player of videos encoded in h.264.

**Comment by jstkdng** [comment]
can you upload that screenshot? maybe it has some weird format

**Comment by jackj1** [comment]
> can you upload that screenshot? maybe it has some weird format

sorry i'm not really sure what you mean, was the screenshot I uploaded in the first post not ok, should I upload it somewhere else and link it? or give some more examples?

**Comment by jstkdng** [comment]
nvm, the first file is fine

it seems that image is using 16 bits per channel, seems `opencv` doesn't support that.

I'd say switch to using only libvips. Create a file `~/.config/ueberzugpp/config.json` with the content

```json
{
    "layer": {
        "no-opencv": true
    }
}
```

**Comment by jackj1** [comment]
thanks, this fixed the rendering of the image in my terminal but it has caused an unwanted side effect, as i scroll through images in lf, the terminal fills in with unwanted text which eventually obscures the whole window.

![ss-23-08-22_16-17_11](https://github.com/jstkdng/ueberzugpp/assets/62434031/ecddb5c8-0d67-4e28-aa82-16b65c00909c)
![ss-23-08-22_16-19_01](https://github.com/jstkdng/ueberzugpp/assets/62434031/3b6f4250-fbba-46cd-9340-4a9f9c4f4f0d)

**Comment by jstkdng** [comment]
are you using arch? if so, switch to `libvips-git` from the aur
