### ISSUE TITLE
spdlog lib error

### ISSUE THREAD

**Issue by niksingh710** [jstkdng/ueberzugpp#119]
so i am using `spdlog-git` for waybar-hyprland-git to work properly and it seems because of this ueberzug fails to find `libspdlog.so.1.11`
as spdlog-git provides `libspdlog.so.1.12`

is this fixable?

**Comment by jstkdng** [comment]
`ueberzugpp` will use whatever version is available, if you recently changed spdlog versions, just recompile

**Comment by niksingh710** [comment]
worked.......
if someone on arch stumbles over this 
make sure to clean cache by using `yay -Sc` and then compiling.
