### ISSUE TITLE
Error while loading libOpenEXR-3_X.so.31

### ISSUE THREAD

**Issue by jackj1** [jstkdng/ueberzugpp#126]
First got the error `ueberzug: error while loading shared libraries: libOpenEXR-3_1.so.30: cannot open shared object file: No such file or directory` so I downgraded the openexr package from v3.2.0-2 to v3.1.11-1, then ueberzug still fails but this time with the message `ueberzug: error while loading shared libraries: libOpenEXR-3_2.so.31: cannot open shared object file: No such file or directory`.

**Comment by jstkdng** [comment]
hey, if you are using `libvips-git`, recompile that package and then recompile `ueberzugpp`

**Comment by jackj1** [comment]
thank you
