### ISSUE TITLE
ueberzugpp broken on Arch Linux due to libspdlog.so.1.12 and others.

### ISSUE THREAD

**Issue by sweetbbak** [jstkdng/ueberzugpp#128]
ueberzugpp requires libspdlog.so.1.11, I tried to symlink 12 to 11, but then it runs into a chain of missing .so files like libfmt.so.10 to the old libfmt.so.9, libopencv_videoio.so.407 etc... I'm not sure what I can specifically do to resolve this.

**Comment by sweetbbak** [comment]
I should mention that I'm using the AUR package as well. I may try compiling from source.

**Comment by jstkdng** [comment]
you just need to recompile in order to link against the new version

**Comment by sweetbbak** [comment]
I see, sorry about the unnecessary issue and thanks for the help. I really like your project.
