### ISSUE TITLE
[Question] This won't be able to display high resolution images in Alacritty on macOS, right?

### ISSUE THREAD

**Issue by ngocphamm** [jstkdng/ueberzugpp#129]
Hi,

I have tried to find out the concrete answer, but I don't think I have came across one yet. Tried on my setup (Alacritty, macOS 13.5.2, with or without tmux) with no luck yet.

AFAIK, this is not possible yet? Because higher resolution images can only be displayed using either sixel, kitty, or iTerm image protocols?

Thanks!

**Comment by jstkdng** [comment]
it's not really the resolution, it's the backend. On macos only iterm2, sixel and kitty are available. Alacritty doesn't work oob with any of them. You can compile your own alacritty with patched sixel support or switch to another terminal.

**Comment by ngocphamm** [comment]
Thanks for the answer @jstkdng!
