### ISSUE TITLE
Take position and size of tmux' status bar into account

### ISSUE THREAD

**Issue by xaizek** [jstkdng/ueberzugpp#13]
The code currently assumes that status bar is at the bottom, but that's not always so. It can also take multiple lines (not my case, but should probably be handled as well).

`tmux display -p '#{status},#{status-position}'` can be used to determine whether the status bar is enabled, at the top and also its height.

**Comment by jstkdng** [comment]
Do you have sample config to have the bar at the top and have it be more than 1 line?

**Comment by xaizek** [comment]
This should be enough:
```tmux
set status-position top
set status 2 # values are on/off/2/3/4/5 with "on" meaning 1 line
```
You don't need to fill extra lines, they'll take up space even when empty.

**Comment by jstkdng** [comment]
alright, should be fixed with the latest commit https://github.com/jstkdng/ueberzugpp/commit/6966c4925db9456061e57479028efa4c1eae0adc

I'll create a new release later

**Comment by xaizek** [comment]
Need to add `|| output[0] == "off"` at https://github.com/jstkdng/ueberzugpp/commit/6966c4925db9456061e57479028efa4c1eae0adc#diff-1195811381989424afc28325e7990a7fdcb2a506961f9798f6f4a2a7ea7d78f7R88. Works otherwise, thanks.

**Comment by jstkdng** [comment]
>Not sure that making a release for almost every change is necessary.

perhaps, once this project matures, releases will be slower.
