### ISSUE TITLE
Sometimes fills the terminal with seemingly random characters

### ISSUE THREAD

**Issue by Kabouik** [jstkdng/ueberzugpp#130]
The below video shows what I sometimes observe with `ueberzugpp`. This is in `foot`, but the same happens with other terminal emulators. The video shows it with [lobster](https://github.com/justchokingaround/lobster) ~~but the same happens with [ytfzf](https://github.com/pystardust/ytfzf) too so I think `ueberzug` is the common point.~~ Not sure, can't reproduce in `ytfzf`, so I must have mixed this issue with another. However, it happens in `lobster` only when enabling thumbnails with `ueberzugp`, so I'll open an issue at the `lobster` repository too in case the issue would be with it.

https://github.com/jstkdng/ueberzugpp/assets/7107523/2edc5330-b776-45a6-8ea2-88b4b38082db

You can see first with `./lobster` that when I scroll slowly and images don't change too fast, there is no issue. However if I scroll faster, then immediately the issue occurs. Later, after I cleared the screen, you can see that the issue occurs directly when I use `./lobster -t` (which shows a much longer list of movies; more text and more rows).

It is not clear to me yet what could be the issue, and I found no match in the closed issues. Here are the logs: [ueberzugpp-droidian.log](https://github.com/jstkdng/ueberzugpp/files/12629156/ueberzugpp-droidian.log)

**Comment by jstkdng** [comment]
hello, that's is sadly a known issue. When using `ueberzugpp` and `fzf`, both programs are fighting over the control of the terminal cursor. If `fzf` starts using the terminal cursor while `ueberzugpp` is still drawing an image those characters will appear. It doesn't happen with `ytfzf` maybe because the thumbnails are smaller or because `ytfzf` has all the information fzf would need.

**Comment by Kabouik** [comment]
Meaning the issue is more likey to appear on a slow device because `ueberzugpp` takes longer to draw images? The device is a phone in my case and you can see in the video that images don't show up instantly, so that could explain why the issue happens quite easily (and all the time with `lobster -t`).

Are there potential ways to fix this in the future?

**Comment by jstkdng** [comment]
>Meaning the issue is more likey to appear on a slow device because ueberzugpp takes longer to draw images?

yeah, sadly

>Are there potential ways to fix this in the future?

nope, not on my side. You could see an improvement if you switch from opencv to libvips. (assuming you installed the OBS package).
