### ISSUE TITLE
Image previews isnt removed when opening a video/image with `gokcehan/lf` on Hyprland (wayland)

### ISSUE THREAD

**Issue by noornee** [jstkdng/ueberzugpp#131]
I dont normally use Hyprland but i decided to test it out a bit and i noticed this issue with my image previews. 
i originally thought it had to do with the animations on hyprland but even after i disabled the animation, this issue still persists.

is this a wayland/hyprland thing? cos i never had this issue on BSPWM. 

[preview.webm](https://github.com/jstkdng/ueberzugpp/assets/71889751/9494daed-d73a-4064-a923-cb9fcfdcb6e0)

great project btw!

**Comment by jstkdng** [comment]
hmm, could it be that it did happen but you just didn't notice? Previews don't dissapear when you open a file. On x11 previews are attached to the terminal but on wayland they aren't.

**Comment by noornee** [comment]
> hmm, could it be that it did happen but you just didn't notice? Previews don't dissapear when you open a file.

woww, i didn't know this!
i originally thought they disappear when a file is opened. TIL.

ughh, it's these little things that's stopping me from making a full switch to wayland (>_<)

>On x11 previews are attached to the terminal but on wayland they aren't.

does this mean that there's nothing that could be done ? ;-;

**Comment by jstkdng** [comment]
>does this mean that there's nothing that could be done ? ;-;

you can use the  X11 backend on a terminal that doesn't have wayland support (xterm, urxvt). You can also switch to another backend like sixel, kitty or iterm2.

**Comment by noornee** [comment]
_sighhhhh_, Thanks you ^^
