### ISSUE TITLE
fifo broken on slow hardware

### ISSUE THREAD

**Issue by ghost** [jstkdng/ueberzugpp#133]
it works fine in ranger, it doesn't work in lf. It used to work very slowly (if you remember my other issues). It's completely broken for a few months now. In lf i only see "loading" for a few moments.

i'm on Debian 12 amd64

I still think it's a multitreading bug ( stuff happen in unexpected order).

**Comment by jstkdng** [comment]
Most of the time the fifo or socket live on /tmp, maybe you have faulty ram? Try using the fifo outside from /tmp
