### ISSUE TITLE
[bug] zsh: IOT instruction (core dumped) when using nvim terminal + neovide

### ISSUE THREAD

**Issue by Dimfred** [jstkdng/ueberzugpp#134]
A little related to: #89

When running `ueberzug layer` I get:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  UNABLE TO CALCULATE TERMINAL SIZES
zsh: IOT instruction (core dumped)  ueberzugpp layer
```

From the old ueberzug I know that it had issues calculating the 100% corrent terminal size, the image was normally shifted by 1-2 columns, because the nvim terminal can't 100% correctly forward the size.

If I use another terminal emulator, e.g. `st` everything is fine, so it probably is related to nvim.

Installed on arch (btw), ueberzugpp@v2.9.2

Thanks for the rewrite btw, am really looking forward on using it.

EDIT:
the issue is not with nvim, but rather when I am using it inside neovide

**Comment by jstkdng** [comment]
Neovide isn't a terminal it seems, just a GUI for neovim. I'm not sure how it works or if it will even work. Does regular ueberzug work with neovide?

**Comment by Dimfred** [comment]
Yeah regular ueberzug works. So I am not really sure with whom you talk to get the size of the term, whether it's the emulator who knows the size, or whether it's the window itself.

Since it works in a terminal, where the neovim term is running inside, it seems like it's the highest window, so in this case neovide?

Let me know where I can support.

**Comment by jstkdng** [comment]
I think I managed to fix the issue with the latest commit, do test it.
