### ISSUE TITLE
ueberzuppp support on wayland

### ISSUE THREAD

**Issue by bartlibert** [jstkdng/ueberzugpp#137]
[ueberzugpp](https://github.com/jstkdng/ueberzugpp) supports wayland, but I cannot use it in ctpv because there is an explicit check that disables ueberzug in wayland.

I recompiled with the change below and now image previews are working perfectly.

Probably some better fix could be added (check for ueberzugpp? introduce a forceueberzug flag? ...) but this at least seams to work fine.

```
diff --git a/sh/helpers.sh b/sh/helpers.sh
index fef8691..f194557 100644
--- a/sh/helpers.sh
+++ b/sh/helpers.sh
@@ -52,7 +52,7 @@ set_image_method() {
 	[ -n "$forcekittyanim" ] && is_kitty && is_anim_image && { image_method="$image_method_kitty"; return 0; }
 	[ -n "$forcechafa" ] && exists chafa && { image_method="$image_method_chafa"; return 0; }

-	[ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && exists ueberzug &&
+	exists ueberzug &&
 		[ -n "$fifo" ] && [ -e "$fifo" ] &&
 		{ image_method="$image_method_ueberzug"; return 0; }
````

**Comment by jstkdng** [comment]
uhhhh, did you confuse repos m8? I think you should have opened this issue on the ctpv repository.

**Comment by bartlibert** [comment]
oops, I messed up indeed, really sorry.
