### ISSUE TITLE
Pixelated preview in Ranger under Wayland

### ISSUE THREAD

**Issue by butla** [jstkdng/ueberzugpp#138]
The previews I get with Ranger are pixelated.
![image](https://github.com/jstkdng/ueberzugpp/assets/1710591/6415bb51-b9c6-4b20-bfd7-ee8b1594c3f6)

I use Alacritty, but I get the same result with Kitty.

I'm using ueberzugpp 2.9.2.

Output of `inxi -Gxx`:
```
  Device-1: Intel Alder Lake-UP3 GT2 [Iris Xe Graphics] vendor: CLEVO/KAPOK
    driver: i915 v: kernel arch: Gen-12.2 ports: active: eDP-1 empty: DP-1,
    DP-2, DP-3, DP-4, HDMI-A-1 bus-ID: 00:02.0 chip-ID: 8086:46a8
  Device-2: Bison BisonCam NB Pro driver: uvcvideo type: USB rev: 2.0
    speed: 480 Mb/s lanes: 1 bus-ID: 3-7:2 chip-ID: 5986:214c
  Display: wayland server: X.org v: 1.21.1.8 with: Xwayland v: 23.2.0
    compositor: gnome-shell v: 44.4 driver: X: loaded: modesetting
    alternate: fbdev,vesa dri: iris gpu: i915 display-ID: 0
  Monitor-1: eDP-1 model: ChiMei InnoLux 0x1408 res: 1920x1080 dpi: 158
    diag: 354mm (13.9")
  API: EGL v: 1.5 platforms: device: 0 drv: iris device: 1 drv: swrast gbm:
    drv: iris surfaceless: drv: iris wayland: drv: iris x11: drv: iris
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 23.1.7-1 glx-v: 1.4
    direct-render: yes renderer: Mesa Intel Graphics (ADL GT2)
    device-ID: 8086:46a8 display-ID: :0.0
```

If I log in with an X11 session, the previews fine.

**Comment by jstkdng** [comment]
hmm, you are using gnome wayland. Check this comment to fix the issue. https://github.com/jstkdng/ueberzugpp/issues/81#issuecomment-1623923211

**Comment by butla** [comment]
@jstkdng Thanks. That works for Kitty. Sadly not for Alacritty (I tried "kitty" and "sixel" settings), and not for Kitty under Tmux.

I should've mentioned in my original post that I'm using Tmux.

**Comment by jstkdng** [comment]
tmux + gnome wayland is not supported sadly
