### ISSUE TITLE
Cache is broken

### ISSUE THREAD

**Issue by theartful** [jstkdng/ueberzugpp#142]
I've been using ueberzugpp for a while now, and it's been great. But recently, I would occasionally get previews that consisted only of noise, and even sometimes I would get completely wrong previews (for other files with completely different names and paths). After disabling the cache "--no-cache" all of this was solved.

This didn't happen all the time. I would run the preview of the same file multiple times consecutively, and sometimes I get the correct preview, and others I don't.

I know this bug report is not much of a help, but I intend to track and fix the bug when I get the time.

EDIT: Probably not caching. There is some sort of memory corruption happening

**Comment by jstkdng** [comment]
Are you using opencv or libvips?

**Comment by theartful** [comment]
Yes I was using both. I had an example that consistently triggered this problem locally, but after updating the system and restarting, the problem has disappeared. So I'm going to assume that it was because of a faulty dependency and it has been fixed (rolling release problems).

I will close this for now, and if it reappeared, I will reopen and work on a fix. Sry for wrong call.
