### ISSUE TITLE
--silent does not suppress output from libvips

### ISSUE THREAD

**Issue by diniamo** [jstkdng/ueberzugpp#144]
As the title says, `--silent` does not suppress output from libvips, which is a big problem for TUI apps.
These are the lines that I'm mostly getting:
```
vips_image_dispose: temp-107 vips_reduceh_gen computed 200%
vips_image_dispose: temp-106 vips_reducev_vector_gen computed 200%
```

The even bigger problem is that it's stdout, and piping stdout to `/dev/null` breaks the displayed images for some reason.

From my experience, OpenCV fails with some images, that's why I want to use libvips.

**Comment by diniamo** [comment]
https://github.com/libvips/libvips/blob/27e8688554c104da72e27300df2f0da00985523f/libvips/iofuncs/image.c#L489-L505

Found the culprint, I wonder why that is set when I installed libvips from Arch repos.

**Comment by diniamo** [comment]
Turns out it's the fault of the arch libvips package maintainers: https://bugs.archlinux.org/task/79527

Closing.

**Comment by jstkdng** [comment]
Indeed, you can switch to `libvips-git` in the meantime

**Comment by diniamo** [comment]
Yup, I've done that.
