### ISSUE TITLE
AMD not displaying image

### ISSUE THREAD

**Issue by arminveres** [jstkdng/ueberzugpp#145]
I compiled the binary from source and on my intel based laptop it works, while with amd it displays some weird buffer problems.
I get the same results both on ranger and on vifm (with vifmrun). All required packages were installed, including OpenCV.
```
[ INFO:0@0.045] global registry_parallel.impl.hpp:96 ParallelBackendRegistry core(parallel): Enabled backends(2, sorted by priority): TBB(1000); OPENMP(990)
[ INFO:0@0.045] global parallel_for.tbb.hpp:54 ParallelForBackend Initializing TBB parallel backend: TBB_INTERFACE_VERSION=11103
[ INFO:0@0.045] global parallel.cpp:77 createParallelForAPI core(parallel): using backend: TBB (priority=1000)
```
![image](https://github.com/jstkdng/ueberzugpp/assets/45210978/dccdec1e-c596-4472-abfb-79eb168d0c7b)

Additionally I also get sometimes errors that get covered in an instant, so I don't have time to capture them fully.
`'/usr/lib64/clc/gfx1030-amdgcn-mesa-mesa3d.bc': no such file or directory`

OS: Fedora 38
Mesa: 23.1.8-1

**Comment by jstkdng** [comment]
maybe you are missing an opencl implementatioin for amd. Try installing mesa-opencl or rocm if your gpu is supported. Otherwise, switch to using libvips only.

**Comment by arminveres** [comment]
Hey @jstkdng, thanks I tried installing `mesa-libOpencl` and `rocm-opencl` to no avail. Libvips also does not display the images, although I am not getting any logs/infos on that. Both sometimes display some images, I was not able to discern what the different is though.

**Comment by jstkdng** [comment]
is this still an issue?
