### ISSUE TITLE
Image not quite aligned to text (Alacritty)

### ISSUE THREAD

**Issue by randomcoder67** [jstkdng/ueberzugpp#147]
I also tested this in kitty and the same thing appears to happen. 

The gap on the right between the bar is not the same as the gap on the left, the image is a few pixels too far to the right. It's not just the line character I'm using, if you highlight the surrounding terminal "cells" it is also slightly off. 

Is there any way to fix this? 

![temp](https://github.com/jstkdng/ueberzugpp/assets/135234789/f0915670-8577-4e72-b3df-d3f318e63b72)

I'm running on Arch Linux, with Alacritty `alacritty 0.12.3 (5efb0690)`, and I compiled ueberzugpp from a clone of the git repo today.

**Comment by jstkdng** [comment]
are you on x11?

**Comment by randomcoder67** [comment]
> are you on x11?

Yes, X11 with Xfwm4

**Comment by randomcoder67** [comment]
I think I found a solution for alacritty, you need to set:

```
window:
 dynamic_padding: true
```
in your alacritty.yml

I've found a few issues in some other terminal emulators though, I think I'll make a new issue for that as it's different to this issue

**Comment by jstkdng** [comment]
closing if no longer an issue
