### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by zhackk** [jstkdng/ueberzugpp#150]
Giving me this error while compiling 
[ 95%] Building CXX object CMakeFiles/ueberzug.dir/src/image/libvips.cpp.o
[100%] Linking CXX executable ueberzug
/usr/bin/ld: warning: libimagequant.so.0, needed by /usr/lib/libvips.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib/libvips.so: undefined reference to `liq_set_dithering_level'
/usr/bin/ld: /usr/lib/libvips.so: undefined reference to `liq_set_speed'
/usr/bin/ld: /usr/lib/libvips.so: undefined reference to `liq_set_max_colors'
/usr/bin/ld: /usr/lib/libvips.so: undefined reference to `liq_attr_create'
/usr/bin/ld: /usr/lib/libvips.so: undefined reference to `liq_image_create_rgba'
/usr/bin/ld: /usr/lib/libvips.so: undefined reference to `liq_get_palette'
/usr/bin/ld: /usr/lib/libvips.so: undefined reference to `liq_write_remapped_image'
/usr/bin/ld: /usr/lib/libvips.so: undefined reference to `liq_image_add_fixed_color'
/usr/bin/ld: /usr/lib/libvips.so: undefined reference to `liq_set_quality'
/usr/bin/ld: /usr/lib/libvips.so: undefined reference to `liq_attr_destroy'
/usr/bin/ld: /usr/lib/libvips.so: undefined reference to `liq_image_quantize'
/usr/bin/ld: /usr/lib/libvips.so: undefined reference to `liq_result_destroy'
/usr/bin/ld: /usr/lib/libvips.so: undefined reference to `liq_image_destroy'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ueberzug.dir/build.make:468: ueberzug] Error 1
make[1]: *** [CMakeFiles/Makefile2:166: CMakeFiles/ueberzug.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

I use arch btw, i have libvips and libimagequant installedd

**Comment by jstkdng** [comment]
A lot of other projects broke after the `libimagequant` upgrade, I'd suggest you switch to `libvips-git`.

**Comment by zhackk** [comment]
Thanks bro.
