### ISSUE TITLE
bug report: high cpu usage when X server is killed with ueberzug used in a tmux session

### ISSUE THREAD

**Issue by maki40681** [jstkdng/ueberzugpp#151]
1. running ranger in a tmux session and used the image preview functionality at least once
2. detached the tmux session with ueberzug still previewing image or not
3. kill X or logout & login
4. high usage of 1 cpu core and increased temperature, even without re-attaching to session & without restarting X

same happens when tmux is detached while viewing ytfzf thumbnails and X is killed. only in a tmux session. fine in a temporary terminal instance

**Comment by jstkdng** [comment]
this is quite the specific issue. Please do `export SPDLOG_LEVEL=debug` before reproducing the issue, then post the log here.

**Comment by maki40681** [comment]
I tried doing as directed, but no output was printed. Researching about ways debugging using spdlog didn't yield anything. Please make the debugging steps clearer.

**Comment by jstkdng** [comment]
oh, my bad, the output log is located on `/tmp/ueberzugpp-$USER.log`

**Comment by maki40681** [comment]
[ueberzugpp_ranger.log](https://github.com/jstkdng/ueberzugpp/files/13328681/ueberzugpp_ranger.log)
[ueberzugpp_ytfzf.log](https://github.com/jstkdng/ueberzugpp/files/13328682/ueberzugpp_ytfzf.log)
