### ISSUE TITLE
failed configuring u++ before build

### ISSUE THREAD

**Issue by adetabrani** [jstkdng/ueberzugpp#152]
![1699796075_Nov12_20:34:35](https://github.com/jstkdng/ueberzugpp/assets/47938004/c59fc086-a397-4cfa-8410-4a85c7ed93bb)

recently I upgraded to fedora 39, and u++ preview didn't work on my LF, I tried to rebuild but I got this error when configuring,
I tried searching for the path and I didn't find sysprof-4 but instead I found the path "/usr/include/sysprof-6"

how to solve this issue?

**Comment by jstkdng** [comment]
hmm, I'd say delete all the contents of the build dir and try to make a clean build. Do you have vips-devel-8.14.2-2.fc39 installed?

**Comment by adetabrani** [comment]
solved, thanks for the help
