### ISSUE TITLE
Pixelated output on wayland in foot terminal (vifm)

### ISSUE THREAD

**Issue by vacuumbeef** [jstkdng/ueberzugpp#157]
Basically getting the same results shown in https://github.com/jstkdng/ueberzugpp/issues/138, https://github.com/jstkdng/ueberzugpp/issues/81 and https://github.com/jstkdng/ueberzugpp/issues/93 but in foot terminal using Vifm. Not sure what I need to do to display images properly.

**Comment by jstkdng** [comment]
Do the same as in this comment `https://github.com/jstkdng/ueberzugpp/issues/81#issuecomment-1623923211` and replace `kitty` for `sixel` unless you want to use the wayland backend in which only sway, hyprland and wayfire are supported.

**Comment by vacuumbeef** [comment]
I'm sorry I was stupid.
For some reason I had output set to "foot" long ago and I forgot about it. Setting it to "sixel" makes everything work as it should.
