### ISSUE TITLE
Support EXIF orientation tag

### ISSUE THREAD

**Issue by avidseeker** [jstkdng/ueberzugpp#159]
Example image: https://commons.wikimedia.org/wiki/File:Statue_of_Averroes_in_C%C3%B3rdoba,_Spain.jpg

nsxiv shows this image upright, but ueberzugpp previews it horizontally.

**Comment by jstkdng** [comment]
Can you show some pictures of the issue? I'm getting a correct preview.
![image](https://github.com/jstkdng/ueberzugpp/assets/52050345/b3830b2e-b9b7-4457-8893-618fd5171afa)

**Comment by avidseeker** [comment]
```sh
{"action": "add", "identifier": "preview", "max_height": 43, "max_width": 88, "path": "/home/user/d/pic.jpg", "x": 90, "y": 2}
````

![image](https://github.com/jstkdng/ueberzugpp/assets/67508272/98f9f6fd-1ade-49dd-a9fe-3ecec168c178)

**Comment by jstkdng** [comment]
Alright, please upload the picture so I can test it, maybe the one I downloaded doesn't have the issue.

**Comment by avidseeker** [comment]
Direct link: https://upload.wikimedia.org/wikipedia/commons/a/a2/Statue_of_Averroes_in_C%C3%B3rdoba%2C_Spain.jpg

Sha1:
```
f2585e69e97e4686cff7aac335204aafedfde018  Statue_of_Averroes_in_Córdoba,_Spain.jpg
```

**Comment by jstkdng** [comment]
On which platform are you on? The image i have has the same sha1sum

**Comment by avidseeker** [comment]
Arch Linux using st terminal:

![image](https://github.com/jstkdng/ueberzugpp/assets/67508272/8547192d-89f8-48b0-aea3-7de25b2e62ad)

**Comment by jstkdng** [comment]
alright, I was able to reproduce the issue. I'll look into it.

**Comment by jstkdng** [comment]
should be working on master. libexif is required now.
