### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by AnonymouX47** [jstkdng/ueberzugpp#16]
I believe the author of ueberzug had very clear and sincerely good reasons to put the project to rest. From the README:

> it was thought to help during the time in which these protocols are supported to rarely.
> ...
> Such an tool may also increase the adoption time of these image protocols which is why I suggest not to fork this project,
> but to move to one of the terminal emulators which have image support.

The sudden absence of ueberzug might seems harsh on project already depending on it but it's for the better. The earlier those projects move on to well-established protocols (rather than "hacks"), the better. This will also encourage terminal emulator developers to adopt and implement these protocols.

If this project goes on, I fear the efforts and intentions of ueberzug's author will all come to nought. I hate to be that dude that tells someone to stop a project they feel they should work on but **please, think about the implications**.

Thank you.

**Comment by jstkdng** [comment]
> Why?

Because I want to give users and developers an easier time using/supporting those protocols. Supporting sixel/iterm2/kitty is no simple task.

> The earlier those projects move on to well-established protocols (rather than "hacks"), the better

I agree, that's why U++ supports the "hack" (x11 child windows) and other well stablished protocols (just sixel for now but plan to support iterm2 and kitty).

**Comment by AnonymouX47** [comment]
> Because I want to give users and developers an easier time using/supporting those protocols.

Hmm 🤔... but note that that's exactly what the author was trying to get at, easier == longer.

Anyways, you should add a note of advice concerning this, probably somewhere immediately visible in the project's README. As it is right now, this project seems to be majorly advertised as another project just like ueberzug.

**Comment by AnonymouX47** [comment]
Something advising users to embrace and move on to using established protocols instead of the hack.

To be sincere, the problem isn't actually solved as long as some project out there still implements this hack. Only in the absence of such hacks can TE developers be pushed to implement support for these protocols, be it by increased user requests or by realization of the developers that there isn't any means of displaying images in the terminal emulator.

I hope you'll see my point and do what's best for the future of TEs.

Thanks :smiley:

**Comment by jstkdng** [comment]
>can TE developers be pushed to implement support for these protocols

you can't really force devs to implement stuff, or even force them to accept PRs (like seebye with OG ueberzug). In the free market place of projects, users will use what they need and stuff that is not used will fall into obscurity.

>there isn't any means of displaying images in the terminal emulator.

even this usecase is somewhat niche, I'd say only WM users are interested in this as ppl that use DE will just use their DEs filemanager and that should display thumbnails. As long as wayland WM users are a minority things won't change.

**Comment by akashpal-21** [comment]
This post was so idiotic it's beyond comprehension. What are we on Xorg to do? Follow suit of RedHat(TM) and go onto Wayland? Wayland is junk that breaks multiple established projects. From a user stand point, Wayland is absolute rubbish. Multiple projects rely on this and it's borderline moronic to suggest the dev to do what this poster suggests. It was the original Devs prerogative to delete everything and post the passive aggressive soydev note, for another person to cite that as canon is NPC level act. 

I wholeheartedly wish to thank this dev for putting this together and continuing this project and supporting us against this onslaught of anti-unix crusade by these corporations secretly undermining the community driven nature of gnu and their nibwit NPC supporters. 

Sorry for language but reading this made me want to do evil things

**Comment by jstkdng** [comment]
lmao, thanks for the support I guess.

This project supports wayland now btw, only sway though.

**Comment by AnonymouX47** [comment]
@akashpal-21 I'm sorry you feel that way.

I opened this in good faith (not necessary you see it that way though).
My sincere apology goes to the author and anyone else who may feel offended by my words or the way I put them together. 🙏🏾

The author explained the motive behind and the goal of the project back then and over time, I've come to understand and see it's different from my initial thoughts.

Sorry and Thanks.

By the way, well done thus far @jstkdng.
