### ISSUE TITLE
EGL issue

### ISSUE THREAD

**Issue by santoryudeadman** [jstkdng/ueberzugpp#161]
when trying to run lobster this is the error i get, my spdlog is latest . I also cant see pictures through ranger as well.

ueberzugpp: symbol lookup error: ueberzugpp: undefined symbol: eglCreatePlatformWindowSurface

i cant understand why it wont work. This all started to happen when i upgraded the packages

**Comment by santoryudeadman** [comment]
im on arch linux by the way

**Comment by santoryudeadman** [comment]
so i removed and reinstalled the aur package for ueberzugpp and even did the same for lobster-git as well and im still having the same error with lobster and ueberzugpp not working with ranger

**Comment by santoryudeadman** [comment]
I completely forgot this PC was older and without gl.  But yes this new package worked completely. This is a great option for stuff not on x11. Thanks a lot

**Comment by jstkdng** [comment]
alright then, closing
