### ISSUE TITLE
Image rendering won't work after updating  spdlog on arch

### ISSUE THREAD

**Issue by VPavliashvili** [jstkdng/ueberzugpp#164]
today after updating  spdlog (1.12.0-2 -> 1.13.0-1), ueberzugpp won't render images anymore. I tried to downgrade package and it went back to normal.

the error says following:
ueberzug: error while loading shared libraries: libspdlog.so.1.12: cannot open shared object file: No such file or directory

I went on spdlog github repository and tried to inspect the commits, but could not find anything helpful(not proficient with cpp unfortunately)
this is diff between their v13 adn v12 tags fwiw
[https://github.com/gabime/spdlog/compare/v1.12.0...v1.13.0](https://github.com/gabime/spdlog/compare/v1.12.0...v1.13.0)

**Comment by Captniz** [comment]
Same problem here

**Comment by jstkdng** [comment]
you only need to rebuild ueberzugpp, it should work fine after that
