### ISSUE TITLE
No remove listener for sixel ?

### ISSUE THREAD

**Issue by Nevrdid** [jstkdng/ueberzugpp#166]
Hi,
I would like to have the preview for my konsole + tmux + ranger setup so i installed ueberzugpp with tmux-sixel-git from aur.
So the images are well display however they are not removed once i switch file to preview. It work well when i set the ueberzug output to tmux but, with it, the preview is pixelated.
So I wonder if it's suposed to work like that or if the remove handler is just missing for sixel and so it's the expected behavior?
I tried differents settings in conf with/without stdin and escapes-codes but it not change anything. I also did some experiments in the ranger preview code to redraw, refresh flush etc after the remove call but it not change anything.
Thanks.
Edit: I forgot to say i'm under wayland's KDE

**Comment by jstkdng** [comment]
Hey, sixel + tmux is not supported. Does u++ work well without it?

**Comment by Nevrdid** [comment]
I didn't try but yeah the issue is the same out of tmux.  I quickly tried with yazi which i not usually use but i installed it to try how it handle it.
Strangely the comportement is the same within tmux but it work well out of tmux.
So i really not know what is causing the issue rn.
I guess as it work out of tmux for yazi it may be tmux but as it not work out of tmux with ranger ....

**Comment by Nevrdid** [comment]
Here is a screen capture of the 4 scenarios:
[Screencast_20240225_210457-1.webm](https://github.com/jstkdng/ueberzugpp/assets/13476270/9fb9b7c2-f184-44cd-bc81-c5e63f6215f7)

**Comment by jstkdng** [comment]
when it comes to sixel, yazi uses it's own implementation outside of u++. Displaying and cleaning.

It seems that konsole doesn't support u++'s cleanup subroutine, not much I can do. Konsole also supports kitty IIRC and that could work.

**Comment by jstkdng** [comment]
No response from OP for some time now, closing
