### ISSUE TITLE
Wayland 用yazi不能预览图片,lf预览图片位置不对

### ISSUE THREAD

**Issue by yuzhegan** [jstkdng/ueberzugpp#169]
config  :~/.config/ueberzugpp/config.json
{
	"layer": {
		"silent": true,
		"use-escape-codes": true,
		"no-stdin": true,
		"output": "x11"
	},
	"action": "add",
	"identifier": "preview",
	"max_height": 0,
	"max_width": 0,
	"path": "/path/image.ext",
	"x": 0,
	"y": 0
}

LF preview image position is incorrect,![1709966554485.png](https://gitss.oss-cn-shenzhen.aliyuncs.com/md/1709966554485.png)
lfub, preview Official repository,
yazi cannot preview images, 
Compile with this:
git clone https://github.com/jstkdng/ueberzugpp.git
cd ueberzugpp
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_TURBOBASE64=ON ..
cmake --build .编译的2.9.4, 
Create a soft link to  /usr/sbin/ueberzugpp, /usr/sbin/ueberzug

**Comment by yuzhegan** [comment]
![1709988588503.png](https://gitss.oss-cn-shenzhen.aliyuncs.com/md/1709988588503.png)
配置文件:~/.config/ueberzugpp/config.json
{
"layer": {
"silent": true,
"use-escape-codes": true,
"no-stdin": true,
"output": "Wayland"
},
"action": "add",
"identifier": "preview",
"max_height": 0,
"max_width": 0,
"path": "/path/image.ext",
"x": 0,
"y": 0
}
图片不清晰,不知到哪里有问题

**Comment by jstkdng** [comment]
Please use english, I don't understand chinese.

>"output": "Wayland"

the output should be all lower case, "wayland", not "Wayland"

**Comment by yuzhegan** [comment]
![1710000280532.png](https://gitss.oss-cn-shenzhen.aliyuncs.com/md/1710000280532.png)
can't show the image use waylandnow, but x11 can show the image, i can change the x11 in set -x XDG_SESSION_TYPE x11,
but x11 the image  is not correct

**Comment by yuzhegan** [comment]
![1710000529483.png](https://gitss.oss-cn-shenzhen.aliyuncs.com/md/1710000529483.png)
![1710000564704.png](https://gitss.oss-cn-shenzhen.aliyuncs.com/md/1710000564704.png)
i use wsl2 gui st Terminal

**Comment by jstkdng** [comment]
Can you try other terminal than `st`? it has issues with `ueberzugpp`

**Comment by jstkdng** [comment]
Closing due to no response from op
