### ISSUE TITLE
  what():  Unable to calculate terminal sizes

### ISSUE THREAD

**Issue by kaiyga** [jstkdng/ueberzugpp#172]
I came to Yazi with this problem. Because Cool-Retro-Term does not have support for image buffering and about ueberzugpp, I know that for this reason it will not render them like it does in Kitty or Xterm

But, yazi uses Chafa for such a case and Ueberzugpp serves as a backend for it.
And since Ueberzugpp cannot start, Chafa in yazi does not work. Paum-Paum

I would like minimal terminall support.

### Software:
- Distribution: Arch Linux
- Kernel: Linux 6.8.1-arch1-1
- DE: GNOME 45.5 (Wayland)
- Term: [cool-retro-term](https://github.com/Swordfish90/cool-retro-term) ($TERM xterm)

### Output: 
```bash
kaiy@archlinux ~> echo "TERM: $TERM | TERM_PROGRAM: $TERM_PROGRAM | XDG_SESSION: $XDG_SESSION_TYPE"                     
TERM: xterm | TERM_PROGRAM:  | XDG_SESSION: wayland

kaiy@archlinux ~> ueberzugpp layer                                                                                      
terminate called after throwing an instance of 'std::runtime_error'                                                     
  what():  Unable to calculate terminal sizes
fish: Job 1, 'ueberzugpp layer' terminated by signal SIGABRT (Abort)

kaiy@archlinux ~ [SIGABRT]> ueberzugpp layer -so chafa                                                                  
fish: Job 1, 'ueberzugpp layer -so chafa' terminated by signal SIGABRT (Abort)  
```

### Log:
```yml
[2024-03-26 21:59:54.988] [terminal] [info] TERM = xterm
[2024-03-26 21:59:54.988] [terminal] [info] PTY = /dev/pts/6
[2024-03-26 21:59:54.988] [terminal] [debug] ioctl sizes: COLS=120 ROWS=52 XPIXEL=0 YPIXEL=0
[2024-03-26 21:59:54.988] [terminal] [debug] iterm2 is not supported
[2024-03-26 21:59:54.989] [terminal] [debug] x11 is not supported
[2024-03-26 21:59:54.989] [terminal] [debug] Wayland is not supported
```

![image](https://github.com/jstkdng/ueberzugpp/assets/92279086/81ae0908-d5a2-4c87-8148-4220b18a2032)

**Comment by jstkdng** [comment]
seems `cool-retro-term` doesn't properly respond to the `TIOCGWINSZ` `ioctl` call, I suggest raising the issue with them.

**Comment by kaiyga** [comment]
Thanks
