### ISSUE TITLE
[Q] what's the latest on running vifm?

### ISSUE THREAD

**Issue by laur89** [jstkdng/ueberzugpp#174]
I'm another refugee from the old ueberzug; common way was to run `vifm` via a shell wrapper.
Could someone please point me to how U++ is to be used in conjunction with vifm?

**Comment by jstkdng** [comment]
vifm has added native support for U++ through a lua plugin. https://github.com/vifm/vifm/tree/master/data/plugins/ueberzug

also, vifmimg still works with U++

**Comment by jstkdng** [comment]
closing due to no show from op
