### ISSUE TITLE
Floating point exception(core dumped) when running wrapper script

### ISSUE THREAD

**Issue by zhackk** [jstkdng/ueberzugpp#175]
I have this script that is a wrapper for lf to start ueberzugpp with it
```
set -e

UB_PID=0
UB_SOCKET=""
UEBERZUG_TMP_DIR="/tmp"

cleanup() {
    exec 3>&-
    ueberzugpp cmd -s "$UB_SOCKET" -a exit
}

if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
    lf "$@"
else
    [ ! -d "$HOME/.cache/lf" ] && mkdir -p "$HOME/.cache/lf"
    UB_PID_FILE="$UEBERZUG_TMP_DIR/.$(uuidgen)"
    ueberzugpp layer --silent --no-stdin --use-escape-codes --pid-file "$UB_PID_FILE"
    UB_PID=$(cat "$UB_PID_FILE")
    rm "$UB_PID_FILE"
    UB_SOCKET="$UEBERZUG_TMP_DIR/ueberzugpp-${UB_PID}.socket"
    export UB_PID UB_SOCKET
    trap cleanup HUP INT QUIT TERM EXIT
    lf "$@" 3>&-
fi
```
when i run this sometimes I get this 
`/home/anonymous/.local/bin/lfub: line 30: 569353 Floating point exception(core dumped) ueberzugpp layer --silent --no-stdin --use-escape-codes --pid-file "$UB_PID_FILE"`
and sometimes it works properly.
How can i fix this?

**Comment by jstkdng** [comment]
Post the log located at `/tmp/ueberzugpp-$USER.log`

**Comment by zhackk** [comment]
I'm sorry, i can't recreate it, I'll post as soon as it occurs again.

**Comment by jstkdng** [comment]
bruh, closing then until you can reproduce
