### ISSUE TITLE
Question: Has anyone been able to get this to work with iTerm2?

### ISSUE THREAD

**Issue by sinkr** [jstkdng/ueberzugpp#178]
Sorry for the question in the issues here--some projects have a discussions forum or Q&A in issues.

I can get this to work in Kitty inside of Tmux, but nothing makes it work in iTerm2 3.5.

**Comment by jstkdng** [comment]
Did you enable the display of images inside iterm2?

**Comment by sinkr** [comment]
Thank you for the plugin and response!

In Tmux 3.5 next, running the test repo https://github.com/csdvrx/sixel-testsuite.git, images display, so I'd have to assume yes, though I don't see an explicit setting for such when I search.

**Comment by jstkdng** [comment]
That's a shame
