### ISSUE TITLE
Fails to build with libc++ 18

### ISSUE THREAD

**Issue by ionenwks** [jstkdng/ueberzugpp#179]
It's an unusual configuration, but received a downstream bug report (https://bugs.gentoo.org/930977) from a user using musl+clang18+libc++ (aka, not libstdc++):
```
ueberzugpp-2.9.4/src/canvas/wayland/config/dummy.hpp:28:10: error: implicit instantiation of undefined template 'std::basic_string<char>'
   28 |     auto get_focused_output_name() -> std::string override { return {}; };
      |          ^
```
I'd say to not waste time trying to reproduce it (unless already have a libc++ system), as can see it's only due to a missing`#include <string>` in dummy.hpp which is probably implicitly included by one of the headers in config.hpp when using libstdc++.

For the record, I did run into a different problem when testing myself (user had disabled X11 so they did not hit it):
```
ueberzugpp-2.9.4/src/canvas/x11/x11.hpp:74:42: error: no member named 'jthread' in namespace 'std'
   74 |     std::unordered_map<std::string, std::jthread> draw_threads;
      |                                     ~~~~~^
```
Seems libc++'s C++20 support is not fully complete and jthread implementation is new and locked behind passing `-fexperimental-library`, imagine that may not work with older versions of libc++ too.

Probably no need to do anything about that one unless want to improve compatibility by dropping jthread usage, we'll just go ahead and pass the option downstream when that configuration is used for now (seems to run fine with it from a simple ueberzug layer test w/ X11).

**Comment by jstkdng** [comment]
>musl+clang18+libc++

unusual indeed

>#include <string> in dummy.hpp which is probably implicitly included by one of the headers in config.hpp when using libstdc++.

yeah, I think `string_view` implicitly includes `string`. I can fix that.

>Probably no need to do anything about that one unless want to improve compatibility by dropping jthread usage,

no it's fine, I can drop jthread. I had to drop it for apple clang so it's no worry

I'll make another release later with the changes

**Comment by jstkdng** [comment]
nevermind, tried to remove jthread from X11 but couldn't do it without adding more complexity, as long as it works...

**Comment by ionenwks** [comment]
Yeah it's fine, having to pass the experimental option will be temporary until some future clang version anyway. Haven't got any reports of there being issues with it so far too. Thanks for trying.
