### ISSUE TITLE
[Core dumped] lfub script file can't run

### ISSUE THREAD

**Issue by R0boter** [jstkdng/ueberzugpp#187]
I update my system, then ueberzugpp can't start, I rebuild it from lastes master branch of, it still not work

System: Archlinux, 
WM: hyprland
Terminal Emulator: foot

this is the error screenshot
![image](https://github.com/jstkdng/ueberzugpp/assets/41858428/adf90e06-8189-49d3-b687-64fbef389272)

this is lfub screenshot
![image](https://github.com/jstkdng/ueberzugpp/assets/41858428/7c5841fa-9127-4c5f-92f4-06bbe44bdce9)

thanks for your help

**Comment by jstkdng** [comment]
it is due to a recent ***breaking*** change in hyprland, should be fixed on the next release

**Comment by jstkdng** [comment]
Fixed on release v2.9.5
