### ISSUE TITLE
Fedora - missing dependencies

### ISSUE THREAD

**Issue by greweln** [jstkdng/ueberzugpp#188]
I'm trying to install Ueberzugpp on Fedora 40 but it requires some opencv libraries v.408.

` Problem: conflicting requests
  - nothing provides libopencv_core.so.408()(64bit) needed by ueberzugpp-2.9.4-4.1.x86_64 from @commandline
  - nothing provides libopencv_imgcodecs.so.408()(64bit) needed by ueberzugpp-2.9.4-4.1.x86_64 from @commandline
  - nothing provides libopencv_imgproc.so.408()(64bit) needed by ueberzugpp-2.9.4-4.1.x86_64 from @commandline
  - nothing provides libopencv_videoio.so.408()(64bit) needed by ueberzugpp-2.9.4-4.1.x86_64 from @commandline
`
Fedora repos provides these libraries as v.409 but apparently there's no backwards compatibility.
I would really appreciate if someone could help me with this.

Thanks

**Comment by jstkdng** [comment]
oh right, forgot to enable fedora 40 builds on the obs. Builds should be available for fedora 40 and ubuntu 24.04 now
