### ISSUE TITLE
Child process 'ueberzug' core dumped

### ISSUE THREAD

**Issue by tifandotme** [jstkdng/ueberzugpp#190]
terminal emulator: alacrity
os: fedora 40

`ueberzug --version`
```bash
ueberzugpp 2.9.5
```

`ueberzug layer`
```bash
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not detect output backend
SIGABRT: child process 'ueberzug' core dumped
```

I got this error. Hoping someone could help me find the solution

EDIT:
I tried running `uberzug layer -o chafa` to load an image manually and it worked. Changing the GNOME version to X11 also worked too, it seems to only occurred on wayland

**Comment by jstkdng** [comment]
Yeah, gnome wayland isnt supported yet

**Comment by tifandotme** [comment]
Just a suggestion, it might be useful to have an option to use chafa explicitly.

**Comment by jstkdng** [comment]
yeah, it should default to chafa instead of crashing. I believe that is a regression, fixed on master
