### ISSUE TITLE
[!] Package contains reference to $srcdir usr/bin/ueberzug

### ISSUE THREAD

**Issue by pirate486743186** [jstkdng/ueberzugpp#191]
building leaks information about the build environment.

I'm actually getting this warning with makedeb, a clone for debs of makepkg. makepkg probably gives the same warning too, but you didn't notice.

the binary works fine.

**Comment by jstkdng** [comment]
Nope, the error doesn't show up with `makepkg`, maybe `makedeb` has an issue.
