### ISSUE TITLE
Error using ueberzugpp in ranger

### ISSUE THREAD

**Issue by doonoo** [jstkdng/ueberzugpp#193]
![ArcoLinux-2024-05-11-1715487855_screenshot_1600x900](https://github.com/jstkdng/ueberzugpp/assets/18385494/9c3e7225-d2ab-41e7-aca7-a047c975fdbf)

**Comment by jstkdng** [comment]
Update your mirrors to updated ones and rebuild `ueberzugpp`, the `spdlog` update happened some days ago
