### ISSUE TITLE
why some random characters shown when I do preview, iterm2

### ISSUE THREAD

**Issue by marsjane** [jstkdng/ueberzugpp#195]
I just refer to the lf config as [doc](https://github.com/jstkdng/ueberzugpp/blob/master/scripts/lf/lfub), and got these random characters:
https://share.cleanshot.com/GswVr9qz
the picture sometimes shows fine(with character), but sometimes just a fast blink then disappears, is there any advice on this?
Btw, can I use stable alacrity with this? I guess it is still not supported, right?

**Comment by jstkdng** [comment]
That is expected and I cant fix it.
Basically, the file manager and u++ are fighting over the control of stdout. If U++ wins, then an image shows up, if she doesnt, garbage shows up
