### ISSUE TITLE
core dumped in vifmrun

### ISSUE THREAD

**Issue by AtomToast** [jstkdng/ueberzugpp#196]
when using https://github.com/thimc/vifmimg/blob/master/vifmrun in my vifm setup to preview images, ueberzugpp recently stopped working and when closing the application I always get an error

```
/home/kjell/.config/vifm/scripts/vifmrun: line 21: 54746 Aborted                 (core dumped) ueberzug layer -s -p json < "$FIFO_UEBERZUG"
```
I'm running wayland with river and my ueberzugpp config file is:

```
{
  "layer": {
    "output": "sixel"
  }
}
```

It worked before, not sure what update may have broken this now

**Comment by jstkdng** [comment]
Can you try compiling from master?

**Comment by AtomToast** [comment]
that works. I guess the aur package/release is out of date?

**Comment by jstkdng** [comment]
There are changes that aren't in a release yet
