### ISSUE TITLE
Socket isn't responding to coordinates

### ISSUE THREAD

**Issue by misterhackerman** [jstkdng/ueberzugpp#197]
![image](https://github.com/jstkdng/ueberzugpp/assets/110896434/1b691d52-bfe7-4838-9e11-20e48f541a94)

lfub:
```sh
#!/bin/sh

# This is a wrapper script for lf that allows it to create image previews with
# ueberzug. This works in concert with the lf configuration file and the
# lf-cleaner script.

set -e

UB_PID=0
UB_SOCKET=""
UEBERZUG_TMP_DIR="/tmp"

cleanup() {
    exec 3>&-
    ueberzugpp cmd -s "$UB_SOCKET" -a exit
}

if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
    lf "$@"
else
    [ ! -d "$HOME/.cache/lf" ] && mkdir -p "$HOME/.cache/lf"
    UB_PID_FILE="$UEBERZUG_TMP_DIR/.$(uuidgen)"
    ueberzugpp layer --silent --no-stdin --use-escape-codes --pid-file "$UB_PID_FILE"
    UB_PID=$(cat "$UB_PID_FILE")
    rm "$UB_PID_FILE"
    UB_SOCKET="$UEBERZUG_TMP_DIR/ueberzugpp-${UB_PID}.socket"
    export UB_PID UB_SOCKET
    trap cleanup HUP INT QUIT TERM EXIT
    lf "$@" 3>&-
fi
```

**Comment by misterhackerman** [comment]
When i restart the X server it is fixed, but it happens again randomly.

**Comment by jstkdng** [comment]
Hey, can you compile from master?

**Comment by misterhackerman** [comment]
I had the package libvips. Now i installed libvips-git. I don't know if this can cause such an issue but so far it didn't reoccur. I'll use it for a while if it reoccurs I'll compile from master.
Should i close the issue till then?

**Comment by jstkdng** [comment]
No, it is not related to libvips. You are not the first one and honestly dont know what could be the problem, could be related to systemd for all I know.

Close it and reopen it if the issue happens again and compiling from master doesnt fix it.

**Comment by misterhackerman** [comment]
is there a variable or a thing that is deleted after X is closed?
like cache or something?

**Comment by misterhackerman** [comment]
https://github.com/jstkdng/ueberzugpp/assets/110896434/36cc9671-55ee-4d12-a9a2-b7b8bfde54b4

Here is how to recreate it, I'll also try with kitty.

**Comment by misterhackerman** [comment]
when i compile i should use `cmake ..` instead of 
`cmake -DCMAKE_BUILD_TYPE=Release ..`
right?

**Comment by misterhackerman** [comment]
I used `cmake ..`
After compiling from master. I can't recreate the Bug. Thanks man.
