### ISSUE TITLE
lf preview black image

### ISSUE THREAD

**Issue by se7en-x230** [jstkdng/ueberzugpp#20]
Not clear where the problem is. But since about 2 days I have a black preview image for all images in lf using uebrzugpp and ctpv

**Comment by jstkdng** [comment]
hey, can you post what does the log at `/tmp/ueberzug_{USER}.log` show?

**Comment by se7en-x230** [comment]
https://0x0.st/H-Lp.log

**Comment by jstkdng** [comment]
what was the last working version? does it work on other terminals?

try executing one of the add commands in a standalone instance of ueberzugpp.

**Comment by se7en-x230** [comment]
Same issu with kitty

how would I use add in a standalone instance?

**Comment by jstkdng** [comment]
>how would I use add in a standalone instance?

like this, run ueberzug then copy the following command for example.
```
$ ueberzug layer
{"action":"add","height":49,"identifier":"preview","path":"/home/seven/Downloads/bg-pattern.png","scaler":"contain","scaling_position_x":0.5,"scaling_position_y":0.5,"width":55,"x":55,"y":1}
```

**Comment by se7en-x230** [comment]
(process:26965): VIPS-WARNING **: 10:41:09.209: unable to load "/usr/lib/vips-modules-8.14/vips-openslide.so" -- libopenslide.so.0: cannot open shared object file: No such file or directory

(process:26965): GModule-CRITICAL **: 10:41:09.212: g_module_make_resident: assertion 'module != NULL' failed
^Cmemory: high-water mark 0 bytes
zsh: no such file or directory: action:add,height:49,identifier:preview,path:/home/seven/Downloads/bg-pattern.png,scaler:contain,scaling_position_x:0.5,scaling_position_y:0.5,width:55,x:55,y:1

**Comment by jstkdng** [comment]
run the first command, then copy the second line.

>what was the last working version? does it work on other terminals?

can you respond this please?

**Comment by se7en-x230** [comment]
I think it started 2 days ago ...  not sure

**Comment by se7en-x230** [comment]
![shop-2023-03-18-10-48](https://user-images.githubusercontent.com/69777713/226083470-b0c1b199-6497-4670-af33-c5ac235d7235.png)

**Comment by jstkdng** [comment]
ok, can you run the same command on kitty but start ueberzugpp with this instead? `ueberzug layer -o kitty`

**Comment by se7en-x230** [comment]
![Uploading shop-2023-03-18-11-15.png…]()

**Comment by se7en-x230** [comment]
![shop-2023-03-18-11-15](https://user-images.githubusercontent.com/69777713/226084366-a060df00-134c-4059-8fd5-34e97debd7cd.png)

**Comment by se7en-x230** [comment]
![shop-2023-03-18-11-20](https://user-images.githubusercontent.com/69777713/226084468-4d7a59fb-38c6-490b-b5de-e02a2aa1a7d7.png)

**Comment by jstkdng** [comment]
ok, it works fine with kitty output. Could this be a regression on dwm or st? Did you update them recently? Seems ueberzugpp is not receiving the appropiate X11 events.

**Comment by se7en-x230** [comment]
I did not with st but I changed something in DWM... let me check another build

**Comment by se7en-x230** [comment]
Nope I build another DWM and ST but both nothing changes

**Comment by jstkdng** [comment]
ok, can you test 2.7.1? I made some changes to the x11 output on 2.7.2 so perhaps I introduced a bug there.

**Comment by se7en-x230** [comment]
sorry I can't see where the  problem is. I downgraded to 2.3. and still the same. 
I installed ueberzug and it works. 

I would like to help to solve this mystery. 
Give me some instructions if you need help

**Comment by jstkdng** [comment]
alright, I can't really replicate your situation since X11 output works fine on my end. Try to use the code on master, if that doesn't work, try to find the last version that worked for you.
Once we have that I can start to investigate.

**Comment by jstkdng** [comment]
no response for some time now, closing.
