### ISSUE TITLE
can not find libopencv_videoio.so.409 on arch

### ISSUE THREAD

**Issue by shadow-absorber** [jstkdng/ueberzugpp#202]
as arch linux updates quickly they have moved on from 4.0.9 of opencv and now on 4.10 hence ueberzugpp seems to fail to run because it can not find the shared library file.... the fix would be to use the one from this link [https://archlinux.org/packages/extra/x86_64/opencv/files/](https://archlinux.org/packages/extra/x86_64/opencv/files/) ... thanks in advance

**Comment by jstkdng** [comment]
only a rebuild is necessary, thanks for reporting. My mirror must be outdated.
