### ISSUE TITLE
libopencv update 4.10

### ISSUE THREAD

**Issue by CaptaiNiveau** [jstkdng/ueberzugpp#203]
Hi, after updating today lfub stopped working with the following message: 
```
ueberzugpp: error while loading shared libraries: libopencv_videoio.so.409: cannot open shared object file: No such file or directory
```
Instead, `/usr/lib/libopencv_videoio.so.410` is available since opencv was updated.

I'll downgrade opencv in the meantime.

Thank you for this repo btw ^^

**Comment by CaptaiNiveau** [comment]
Oh, I tried downgrading opencv, but then it's missing `libavcodec.so.60` which was also updated to version 61, which is provided by ffmpeg. I'll just use lf without ub for the moment.

**Comment by jstkdng** [comment]
Hey, you just need to recompile u++
