### ISSUE TITLE
Image is shown if other tab is focused in sway.

### ISSUE THREAD

**Issue by mo-pyy** [jstkdng/ueberzugpp#204]
ueberzugpp version: 2.9.6

When previewing one image in ranger and than switching to another sway window tab, the image is still shown.

Split screen works:
![screenshot-2024-06-30-17:12:53](https://github.com/jstkdng/ueberzugpp/assets/46331603/6725203f-d7e9-4800-ae5b-ff659523e43c)

Tabbed with ranger focused:
![screenshot-2024-06-30-17:13:33](https://github.com/jstkdng/ueberzugpp/assets/46331603/45fcc618-bc8c-4ae0-9076-02ae04a0b50d)

Tabbed with other window focused (broken):
![screenshot-2024-06-30-17:13:46](https://github.com/jstkdng/ueberzugpp/assets/46331603/c7a03b30-c59d-49fd-8984-15e7b9313f53)

**Comment by jstkdng** [comment]
that is expected. On wayland (except wayfire), images are just floating windows. You can drag them around and stuff.

**Comment by mo-pyy** [comment]
Oh ok I did not know that.  
For anybody else who runs into this behauvior but does not like it:  
Use a terminal (e.g. foot) with sixel support and change the output of ueberzugpp to sixel in the config file. The tabbed sway layout will then just look fine.
