### ISSUE TITLE
X component is off in lf image previews

### ISSUE THREAD

**Issue by noib3** [jstkdng/ueberzugpp#216]
OS: NixOS
WM: Hyprland (Wayland)
Terminal: Alacritty

I'm trying to use ueberzugpp for image previews in lf, however the X component seems to be off. I've checked the value of the `$4`th argument and it's correctly set to `93`, however the preview is positioned many cells to the left of that.

![2024-08-13@14:16:27](https://github.com/user-attachments/assets/c3db0617-4e56-4ebd-b627-39c973ce5826)

The y coordinate, the width and the height are all correct. [This](https://github.com/noib3/dotfiles/blob/dd3f8dd1b710179f2434bcb300976ec74d1298e1/scripts/preview.sh#L33-L39) is the relevant part of my preview script.

**Comment by jstkdng** [comment]
do you have fractional scaling enabled?

**Comment by noib3** [comment]
I usually have 2x scaling, I just changed it to 1x and that seems to solve the issue. Is there a way to make u++ scaling-aware?

**Comment by jstkdng** [comment]
>Is there a way to make u++ scaling-aware?

it kinda is but it works only for native wayland and only in certain cases. Seems xwayland doesn't work properly with fractional scaling. I'll check it out but i can't promise a timeline.

**Comment by noib3** [comment]
What's using xwayland here? I don't think Alacritty is. Also, shouldn't the y component be off as well?

**Comment by jstkdng** [comment]
bruh, sorry, i'm confusing issues.

>Also, shouldn't the y component be off as well

open a terminal below and try to show an image

**Comment by noib3** [comment]
Oh yeah, the y component is off too.

**Comment by jstkdng** [comment]
yeah, supporting fractional scaling is hard. Closing in favor of #189
