### ISSUE TITLE
Missing include for <thread>

### ISSUE THREAD

**Issue by themmj** [jstkdng/ueberzugpp#22]
Building the project from source, I've found that `src/canvas/x11/x11.hpp` is missing the include for `<thread>`. Otherwise the build works fine.

On another note, some dependencies could also be included using `FetchContent`. This would avoid the need to install all dependencies manually beforehand. For example the `cli11` lib is not available in the stable Debian package index, so I included it like this instead:
```cmake
include(FetchContent)
FetchContent_Declare(
    cli11
    GIT_REPOSITORY https://github.com/CLIUtils/CLI11
    GIT_TAG        v2.2.0
)
FetchContent_MakeAvailable(cli11)
```

**Comment by jstkdng** [comment]
>I've found that src/canvas/x11/x11.hpp is missing the include for <thread>

I see, could be related to your compiler version. I'll fix that.

> some dependencies could also be included using FetchContent

what other dependencies apart from `cli11`?

**Comment by themmj** [comment]
Yeah most likely.

I have not checked all of them, but from the top of my head spdlog and nhlohmann's json lib can be included like that.

Btw, the Debian packages for some dependencies might be too outdated, so you'd need to build them from source (e.g. libzmq and cppzmq in my case). This is only distro related, but in case anyone else runs into this, I thought I'd leave that info here.

**Comment by jstkdng** [comment]
alright, adding that manual dependencie compilation could help in those cases.
