### ISSUE TITLE
Config.json ignored

### ISSUE THREAD

**Issue by romain-bury** [jstkdng/ueberzugpp#221]
Hi,

Ueberzugpp seems to ignore the config in my config.json, which is located in the right folder. 
Here is the config.json file : 
`{
  "layer": {
    "use-escape-codes": true
  }
}`

This config file seems to be correctly read by ueberzug, as introducing an error in the syntax (e.g. deleting a "}") raise an error when launching ueberzug. 

Running `ueberzug layer --use-escape-codes` works, but running `ueberzug layer` displays the following error message, despite the config.json : 
`terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to calculate terminal sizes
fish: Job 1, 'ueberzug layer' terminated by signal SIGABRT (Abort)`

Config : WSL2 + Wezterm. 

I'm planning to use ueberzug with images.nvim, so my only option so far is to fork images.nvim to force it to use the "--use-escape-codes" option when calling ueberzug, but perhaps i'm missing something. 

Happy to provide additionnal info if that could help. 

Thanks for your help

**Comment by jstkdng** [comment]
Hey, that is on purpose as escape codes break terminal file managers so usage has to be explicit when required

**Comment by jstkdng** [comment]
no response from op for some time now, closing
