### ISSUE TITLE
Hyprland: Preview doesnt follow moved terminal

### ISSUE THREAD

**Issue by thatDudo** [jstkdng/ueberzugpp#227]
Perhaps you could use .socket2.sock (https://wiki.hyprland.org/hyprland-wiki/pages/IPC/) to listen for move events, and move the preview with it. I guess these are the annoyances that come with using extraneous windows under wayland.
![Screenshot_2024-09-17_02:34:36](https://github.com/user-attachments/assets/9a730ab6-4e04-48cb-801e-0ff64c7a2619)

![Screenshot_2024-09-17_02:34:49](https://github.com/user-attachments/assets/6098930a-8273-4a7d-a146-359c46818286)

**Comment by jstkdng** [comment]
indeed, wayland has no way to attach two surfaces (except wayfire since we have a plugin that does that). I was thinking about writing a hyprland plugin for that (I like the name hyprzug) but before that I wanted to rewrite `ueberzug` to hopefully make it more extendable. https://github.com/jstkdng/ueberzugpp-new

**Comment by thatDudo** [comment]
Hmm, maybe it would be more suitable for that hyprzug plugin to create just one single window on top of the target window to have better performance with multiimage creation. terminal filemanagers could then implement something like a thumbnail view a little better.

**Comment by dybdeskarphet** [comment]
> indeed, wayland has no way to attach two surfaces (except wayfire since we have a plugin that does that). I was thinking about writing a hyprland plugin for that (I like the name hyprzug) but before that I wanted to rewrite `ueberzug` to hopefully make it more extendable. https://github.com/jstkdng/ueberzugpp-new

hey, i know you didn't say you're definetly going to do it but are there any news about it? do you plan to make it?

**Comment by jstkdng** [comment]
>are there any news about it? do you plan to make it?

the rewrite is still ongoing, and I do plan to make the plugin (since I pretty much use hyprland full-time now), but work gets in the way sometimes

thanks for checking in!

I'll create another issue for tracking the plugin + rewrite
