### ISSUE TITLE
Displaying subimage instead of full image

### ISSUE THREAD

**Issue by faerot** [jstkdng/ueberzugpp#229]
I want to implement image view plugin to a terminal-based file manager and I am wondering how to display image with zoom, offset, and clipping using ueberzugpp. The command json format is not very documented apart from few examples so I wonder if there are advanced options to display and image or coords and dimensions is all we have? In order to implement scrolling of large and/or zoomed  images inside terminal window, it would be nice to have more controls over image display like subimage coordinates to display a portion of image resized to fit the desirect rectangular area of the terminal.

**Comment by jstkdng** [comment]
sorry, that is still not implemented yet. OG ueberzug implements that iirc #86
