### ISSUE TITLE
Tor relay embedded in debian package?

### ISSUE THREAD

**Issue by dkragen** [jstkdng/ueberzugpp#233]
I downloaded ueberzugpp .deb and was about to install it, when I thought twice, given xz and other issues cropping up in unverified, undervetted software.  So I uploaded the .deb to VirusTotal to check.  This is what showed up:

![Ueberzuggpp_with_tor_relay](https://github.com/user-attachments/assets/b26d0b93-4ce6-4173-ba25-c8a08efd45e8)

It's interesting that the IDS showed a tor relay and the behavior testing revealed two ip addresses.  The latter I checked as well.  One is a Hetzner instance with an ownership-free certificate.  The other is a Swedish site, again without a valid cert.  

Can any of you explain this?

**Comment by jstkdng** [comment]
What does that mean? That it has IPs somewhere in the file?

**Comment by jstkdng** [comment]
no response from op for some time now, closing, sadly.
