### ISSUE TITLE
can't open libopencv_videoio.so.410

### ISSUE THREAD

**Issue by rxmmah** [jstkdng/ueberzugpp#234]
after installing ub manually, i tried open it and got this:

`ueberzugpp: error while loading shared libraries: libopencv_videoio.so.410: cannot open shared object file: No such file or directory
`
i am on void linux, i downloaded all packages related to opencv and libopencv

**Comment by jstkdng** [comment]
is this still an issue?

**Comment by rxmmah** [comment]
I not on void anymore, i can't build the program.

**Comment by jstkdng** [comment]
closing then, sorry for the delayed response
