### ISSUE TITLE
Homebrew depends on disabled openssl 1.1

### ISSUE THREAD

**Issue by sky0470** [jstkdng/ueberzugpp#235]
Hi,

When I install ueberzugpp with Homebrew, I encounter the error
```
Error: openssl@1.1 has been disabled because it is not supported upstream! It was disabled on 2024-10-24.
```

I believe openssl 1.1 is deprecated and [disabled in Homebrew](https://formulae.brew.sh/formula/openssl@1.1) so it should not be in the dependency list.

Thank you for your help!

**Comment by aleks-krasowski** [comment]
Hey, I managed to install it using this workaround:

1. run `brew install jstkdng/programs/ueberzugpp` and wait for the error message regarding `openssl@1.1`
2. run `brew edit ueberzugpp` and change `depends_on openssl@1.1` to `depends_on openssl@3`
3. run `brew install ueberzugpp`

Didn't encounter any further issues yet.

**Comment by jstkdng** [comment]
my bad, forgot about homebrew since my hackintosh setup died. I will also upgrade it to the latest version when I have the time.

**Comment by jstkdng** [comment]
updated to 2.9.6
