### ISSUE TITLE
Image previews stay visible in non-lf tabs

### ISSUE THREAD

**Issue by Chirunos** [jstkdng/ueberzugpp#239]
![image](https://github.com/user-attachments/assets/0e7028b0-d3a2-4d74-ab3d-aa748244388b)
![image](https://github.com/user-attachments/assets/f8cde9ea-fa9e-4ae8-8e0a-79f4dc9edd17)
ueberzugpp 2.9.6 and Git (both compiled with default options)
lf 31
GNOME Terminal 3.50.1
xfce4-terminal 1.1.1
LXQt 1.4 over KWin 5.27.11 (X.Org)
openSUSE Leap 15.6

I feel like there are workarounds to this that I'm not aware of, please let me know if any exist.

**Comment by jstkdng** [comment]
Yes, that is expected. Under X11, the image is attached to the complete window and tabs aren't separate windows

**Comment by jstkdng** [comment]
I'll take that thumbs up as an acknowledgment
