### ISSUE TITLE
issue with ytfzf

### ISSUE THREAD

**Issue by adetabrani** [jstkdng/ueberzugpp#24]
https://user-images.githubusercontent.com/47938004/231495404-3cb1bd95-e2f5-4185-8266-cd04bd9ec48e.mp4

I'm curious about this bug, is it sourced from ytfzf or from ueberzugpp, ueberzug preview thumbnail for ytfzf only loads once and when selecting another video the thumbnail doesn't load.

and when i quit ytfzf that thumbnail don't disappear in the terminal.

sorry in advance because I'm also not very familiar with the code, maybe you can give some input, however this tool is awesome

**Comment by jstkdng** [comment]
hey, can you show the output of the log file located in /tmp ?

**Comment by jstkdng** [comment]
I've done some testing with ytfzf and it seems it is not sending a clear message after displaying each image. Just added a commit that should fix the issue. Please test master.

**Comment by adetabrani** [comment]
Thank you, works very well.

**Comment by adetabrani** [comment]
One more thing, do the no-opencv and master branches have significant feature differences? Because I build from source and know that there are a lot of depedencies for opencv.

I am currently using the master branch and also disabled the opencv feature in json because there is a bug in my lf preview. i am using fedora 37

**Comment by jstkdng** [comment]
>the thumbnail size and position seems to be different from using the original ueberzug

if OG ueberzg works fine then it's an issue in U++'s side and not ytfzf.

>the original ueberzug will adjust the size of the preview container,

right now I've only implemented the `contain` scaler, the other scalers are not yet implemented for now.

> do the no-opencv and master branches have significant feature differences?

there are no differences between those branches.

>Because I build from source and know that there are a lot of depedencies for opencv.

Compiling U++ without opencv is not in my roadmap right now, you should create an issue for that if you are interested.

**Comment by adetabrani** [comment]
thank you for the responses

**Comment by jstkdng** [comment]
Hey, I've added some initial support for the scaler that ytfzf uses, please do give it a test. And also check if you still have the opencv issue you were mentioning.

Finally, which terminal are you using? I guess those borders are part of the terminal customization?

**Comment by adetabrani** [comment]
> Hey, I've added some initial support for the scaler that ytfzf uses, please do give it a test. And also check if you still have the opencv issue you were mentioning.
> 
> Finally, which terminal are you using? I guess those borders are part of the terminal customization?

thanks, it works.  i'm using simple terminal and alacritty (sixel version)

this is the error i get on LF when activating opencv and on some images it has red layer
![1681458219_Apr14_14:43:39](https://user-images.githubusercontent.com/47938004/231979349-993b009f-44d2-48e4-bc12-2a648146d574.png)

**Comment by jstkdng** [comment]
Ok, I've added some validations to the opencv code, please check it out.

By the way ,do you have any opencl provider installed in your system? like `nvidia-opencl`, `intel-compute-runtime`, `rocm`, `mesa-opencl`?

**Comment by adetabrani** [comment]
> Ok, I've added some validations to the opencv code, please check it out.
> 
> By the way ,do you have any opencl provider installed in your system? like `nvidia-opencl`, `intel-compute-runtime`, `rocm`, `mesa-opencl`?

it looks like the image rendered fine, but the log still appears on my LF.
yes, i'm using intel-compute-runtime

**Comment by jstkdng** [comment]
And does the message return any platforms? last pic said there was 0 platforms found. Is your hardware supported by `intel-compute-runtime`?

You can try silencing it by setting the silent flag in the U++ config. Those logs could also come from the way opencv is compiled in fedora, perhaps there's an env variable documented somewhere. :thinking:

**Comment by adetabrani** [comment]
> 
i've tried enable silent, but it doesn't work

actually I just installed it after you mentioned it 😄, now it seems my opencl has been detected
![1681493151_Apr15_00:25:51](https://user-images.githubusercontent.com/47938004/232116215-2aba7dac-0875-4879-b204-0b4ae5c51dca.png)

**Comment by jstkdng** [comment]
Nice, regarding that logging, seems that you can disable it by configuring this env variable `export OPENCV_LOG_LEVEL=OFF`. I'll add that to the readme.

With that the only thing that isn't working correctly is positioning, does that issue show only on st?

**Comment by sbradnick** [comment]
> With that the only thing that isn't working correctly is positioning, does that issue show only on st?

I notice this type of issue also w/ `st` (specifically); for me, anytime a program like `ranger` loads up a preview w/ `ueberzugpp`, that preview is always in the top, left corner and the rest of the screen is black. I have to click somewhere near the top of the picture for `ranger` to drop me back somewhere else in the fs tree.

I put together my own `st` based off https://github.com/bakkeby/st-flexipatch so I can't say any 2 `st` binaries are the same. But this doesn't happen w/ `xterm` or `urxvt` so I wouldn't say it's a specific U++ problem. I also held off on putting in an issue cause it didn't seem like a general U++ problem, hopefully this +1 here wrt `st` isn't in poor taste.

I use these patches for `st`:

```
- ALPHA_PATCH 1
- BOXDRAW_PATCH 1
- COPYURL_HIGHLIGHT_SELECTED_URLS_PATCH 1
- LIGATURES_PATCH 1
- SCROLLBACK_PATCH 1
- SCROLLBACK_MOUSE_PATCH 1
- SIXEL_PATCH 1
- ST_EMBEDDER_PATCH 1
- XRESOURCES_PATCH 1
- XRESOURCES_RELOAD_PATCH 1
```

**Comment by jstkdng** [comment]
I sadly don't use ST so it's hard to debug, but I've also seen some issues with positioning on other terminals, particularly konsole, mate-terminal and wezterm).

All of these have something in common, that being they have their own menus and tab bars and such. st has none of that afaik.

**Comment by sbradnick** [comment]
> All of these have something in common, that being they have their own menus and tab bars and such. st has none of that afaik.

Yeah, it's pretty 'no-frills' (or maybe 'add your own frills'). If I had to guess, maybe boxdraw is the cause? I could try cutting out various patches and rebuilding to see if a specific one is the cause, I'll try and dig into that next week.

**Comment by adetabrani** [comment]
> Nice, regarding that logging, seems that you can disable it by configuring this env variable `export OPENCV_LOG_LEVEL=OFF`. I'll add that to the readme.
> 
> With that the only thing that isn't working correctly is positioning, does that issue show only on st?

no, alacritty (sixel version) also has the same issue

**Comment by jstkdng** [comment]
>no, alacritty (sixel version) also has the same issue

it does? huh

![image](https://user-images.githubusercontent.com/52050345/232189960-510c26c6-bf00-416b-85c3-b239b55efeb4.png)

I'm also using alacritty with sixel patch and it looks fine. Can you post your config?

**Comment by adetabrani** [comment]
> > no, alacritty (sixel version) also has the same issue
> 
> it does? huh
> 
> ![image](https://user-images.githubusercontent.com/52050345/232189960-510c26c6-bf00-416b-85c3-b239b55efeb4.png)
> 
> I'm also using alacritty with sixel patch and it looks fine. Can you post your config?

![1681540084_Apr15_13:28:04](https://user-images.githubusercontent.com/47938004/232190578-10544533-95c2-42ff-aa2d-debc01ca2473.png)
after disable dynamic_padding in alacritty, I think it's gotten a little bit better , I don't really understand, maybe because I'm using the fork version (sixel)

[here](https://github.com/adetabrani/dotfiles/blob/master/.config/alacritty/alacritty.yml) is my config (note: I haven't pushed in this repository yet)

**Comment by adetabrani** [comment]
![1681541793_Apr15_13:56:33](https://user-images.githubusercontent.com/47938004/232193890-67d506ce-dbf2-4040-bc53-b48be451fe97.png)
I've got a little hint for st, if you apply the [anysize](https://st.suckless.org/patches/anysize/) patch to your st, you will see a preview slightly overlapping the text above it, this behavior seems to be the same as the dynamic_padding config on alacritty (at least mine)

this issue is not necessarily the same for everyone, maybe someone else needs to do this test, because it is feared that this issue only occurs in my system

like your alacritty and mine, the resulting preview output can be different

**Comment by adetabrani** [comment]
> > no, alacritty (sixel version) also has the same issue
> 
> it does? huh
> 
> ![image](https://user-images.githubusercontent.com/52050345/232189960-510c26c6-bf00-416b-85c3-b239b55efeb4.png)
> 
> I'm also using alacritty with sixel patch and it looks fine. Can you post your config?

![1681545683_Apr15_15:01:23](https://user-images.githubusercontent.com/47938004/232198578-5a76155e-6ba8-453a-b963-b7cf5ac7a8e1.png)

sorry before, I want to clarify, apparently I just remembered that I have some FZF config in my .zshrc which causes the position to be problematic, after I disable it, the preview position works very well in st and alacritty

**Comment by Arrow-x** [comment]
![image](https://github.com/jstkdng/ueberzugpp/assets/3308421/5c90fa23-0d94-4aac-be05-519578c69963)
it is back

**Comment by jstkdng** [comment]
you mean the size? One of ytfzf's developers decided to not upscale the thumbnail a while ago.

**Comment by Arrow-x** [comment]
yep you are correct this [commit](https://github.com/pystardust/ytfzf/commit/a46d10dcd9747b4b877e860cd9f00f6086b0bce8) broke it
