### ISSUE TITLE
Building with Turbo-Base64 included

### ISSUE THREAD

**Issue by sbradnick** [jstkdng/ueberzugpp#26]
Just curious if this is going to be a mainstay? Only because most build environments (like https://build.opensuse.org) can't download additional source @ build time via the internet. It would be possible to get those sources ahead of time and include them in the build, but I don't want to dissect `CMakeLists.txt` to attempt to make that work if it's not something for the long term (a la "test fetchcontent").

**Comment by jstkdng** [comment]
hmm, I didn't think about that problem. Fetch content will stay so that it'd be possible to download deps in distros that don't package them or have old versions, #22 being an example, but cmake would first try to find the deps if the are already installed before trying to download anything.

Regarding Turbo-Base64, it was a test for speed and fetchcontent, I'll hide it behind a compile flag so that the OBS can build again. Up to you if you want to package turbo-base64 and test it as well.

Are you compiling from master or releases?

**Comment by sbradnick** [comment]
`master`, since I try to remain as current as I can - considering other factors outside my control (which aren't specific to this project).

I don't know anything specifically about Turbo-Base64 (and it doesn't seem to exist w/in build.opensuse.org in any capacity already), but I could certainly see if I can get it to build as a separate RPM which would be included in the .spec file; so long as it can be separated out from U++ at build time so the `CMakeLists.txt` issue goes away.

**Comment by jstkdng** [comment]
alright, turbo-base64 is now behind a compile flag off by default. Checking if it exists will have to wait until I can package turbo-base64 for arch. It will also require a minimum cmake version of 3.24, is that version available in the obs?

**Comment by sbradnick** [comment]
> alright, turbo-base64 is now behind a compile flag off by default.

U++ builds again w/o any modifications on my side again, thanks!

> It will also require a minimum cmake version of 3.24, is that version available in the obs?

The main version of openSUSE I build for (Tumbleweed) is on 3.26.3 :+1: ; might be a problem for Leap, but that's not something I expect you to be accounting for, esp. if there's a flag for it. `turbo-base64` could always be OFF if the `cmake` requirement isn't present.

> Checking if it exists will have to wait until I can package turbo-base64 for arch.

I won't close this now, unless you'd like to (and I'll keep my eyes on the changelog) - until that's available.

Thanks again :)

**Comment by sbradnick** [comment]
> RIP, at least updating cmake is easy.

In theory, for an end user building from source - sure, but for using a build environment so packages can be provided by repos, not so much. Leap is positioned between a 'rolling release' (Tumbleweed, aka TW) and [is much closer to an] 'enterprise release', so in terms of _use more updated package(s)_ it's not much of an option at build time. Looks like (current) Leap 15.4 uses `cmake` v3.20.4 and the upcoming 15.5 will be using that as well. But that's not a bridge I intend to cross anytime soon as a 99.9% of the time Tumbleweed user. Maybe if someone saw U++ sitting in my home repo and really wanted a Leap build, I'd cross that bridge - but I haven't submitted U++ to Factory for inclusion at this point.

> I have added some changes to check the existence of libraries, hope it won't break OBS now.

63a3b72 built w/o issue :+1:

**Comment by jstkdng** [comment]
>cmake v3.20.4

oof, I've made some changes to support 3.18 in the meantime. Should support leap and debian buster.
