### ISSUE TITLE
Debian 11 stable cmake problem

### ISSUE THREAD

**Issue by og900aero** [jstkdng/ueberzugpp#31]
I want to try build on Debian 11 Stable:

when i use command: cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_X11=ON -DENABLE_OPENCV=OFF ..
get error message:

CMake Error at CMakeLists.txt:39 (find_package):
  By not providing "Findcppzmq.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "cppzmq", but
  CMake did not find one.

**Comment by jstkdng** [comment]
Do you have cppzmq installed? I think it is called cppzmq-dev in debian.

**Comment by og900aero** [comment]
> Do you have cppzmq installed? I think it is called cppzmq-dev in debian.

No. I dont find cppzmq or similar package.

**Comment by jstkdng** [comment]
I see, cppzmq is not available for debian 11. https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=cppzmq

You should be able to install that .deb I think, the only dependency is available for stable and old-stable.
