### ISSUE TITLE
Little mistake with fzfub script

### ISSUE THREAD

**Issue by debeetle** [jstkdng/ueberzugpp#32]
# run fzf with preview
`fzf --preview='ueberzugpp cmd -s $SOCKET -i fzfpreview -a add -x $X -y 1 --max-height $FZF_PREVIEW_COLUMNS --max-height $FZF_PREVIEW_LINES -f {}' --reverse "$@"`
It seems that there need to replace one `--max-height` with `--max-width` to get the script work, 
so 
`fzf --preview='ueberzugpp cmd -s $SOCKET -i fzfpreview -a add -x $X -y 1 --max-width $FZF_PREVIEW_COLUMNS --max-height $FZF_PREVIEW_LINES -f {}' --reverse "$@"`

Anyway, thanks for writing this tool

**Comment by jstkdng** [comment]
Thanks for reporting this, should be fixed now.
