### ISSUE TITLE
issue: TBB error on mac when building

### ISSUE THREAD

**Issue by justchokingaround** [jstkdng/ueberzugpp#33]
after running this build command on mac : `cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_APPLE_SILICON_PROCESSOR=arm64 ..`, i get the following error:
```
CMake Error at CMakeLists.txt:39 (find_package):
  By not providing "FindTBB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "TBB", but
  CMake did not find one.

  Could not find a package configuration file provided by "TBB" with any of
  the following names:

    TBBConfig.cmake
    tbb-config.cmake

  Add the installation prefix of "TBB" to CMAKE_PREFIX_PATH or set "TBB_DIR"
  to a directory containing one of the above files.  If "TBB" provides a
  separate development package or SDK, be sure it has been installed.`
  ```

**Comment by jstkdng** [comment]
Install tbb with homebrew. I also just created a homebrew formula if you'd like to build with it.

**Comment by justchokingaround** [comment]
i am now getting this:
```
-- Checking for module 'xcb-image'
--   No package 'xcb-image' found
CMake Error at /opt/homebrew/Cellar/cmake/3.26.3/share/cmake/Modules/FindPkgConfig.cmake:607 (message):
  A required package was not found
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.26.3/share/cmake/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
  CMakeLists.txt:100 (pkg_check_modules)
  ```
  
  where is your homebrew formula i could use? your homebrew-core fork doesn't seem to contain it

**Comment by jstkdng** [comment]
I'm improving the formula before submitting it to core. Here's the file in the meantime. https://github.com/jstkdng/ueberzugpp/blob/master/homebrew/ueberzugpp.rb

Try installing it with `brew install ueberzugpp.rb`

**Comment by justchokingaround** [comment]
```
  * The installation package was faulty and references files it does not
  provide.

-- Generating done (0.0s)
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING
    CMAKE_INSTALL_LIBDIR


CMake Generate step failed.  Build files cannot be regenerated correctly.

Do not report this issue to Homebrew/brew or Homebrew/homebrew-core!
```

**Comment by jstkdng** [comment]
There's an issue with one dependencie, libmatio. Just edit the file `/usr/local/lib/pkgconfig/matio.pc` and remove this part from the cflags line.

![image](https://user-images.githubusercontent.com/52050345/236700528-f8ac78a3-1132-42a4-981f-196086c6c26b.png)

It needs to be reported but I'm not sure to where.

**Comment by justchokingaround** [comment]
for some reason, that file doesn't exist on my computer, even though the package is installed. i've also tried reinstalling it, but that didn't work:
<img width="724" alt="image" src="https://user-images.githubusercontent.com/44473782/236700873-6fdb2a57-c943-4e57-a161-5e20ca6a21ab.png">

**Comment by jstkdng** [comment]
Is there no pc while when you run `brew list libmatio` ?

![image](https://user-images.githubusercontent.com/52050345/236701000-d2d83797-e4a8-46da-9f11-f394aea0179f.png)

There's one in my case.

**Comment by justchokingaround** [comment]
that worked! my matio.pc was actually in `/opt/homebrew/Cellar/libmatio/1.5.23_1/lib/pkgconfig/matio.pc`. thank you so much :)
<img width="1038" alt="Screenshot 2023-05-07 at 23 09 01" src="https://user-images.githubusercontent.com/44473782/236702654-78b3bffb-452e-4546-9590-4b7d293c761c.png">

**Comment by jstkdng** [comment]
Would you be able to test ytfzf in kitty? I'm unable to test kitty on a vm sadly.

**Comment by justchokingaround** [comment]
i tested it in wezterm using `-t -T iterm2` and `-t -T sixel` and `-t -T kitty` and they all seemed to work, showing the same result

**Comment by jstkdng** [comment]
awesome, thanks for the test.
