### ISSUE TITLE
ueberzugpp doesn't work correctly with terminal padding

### ISSUE THREAD

**Issue by yarled-up** [jstkdng/ueberzugpp#36]
When using programs like ranger and ytfzf that display image previews, they don't display the images in the correct position when terminal padding is enabled. I have tested this with both ranger and ytfzf in the alacritty, st, and kitty terminals. It displays the image as if no padding was applied to the terminal, meaning the text is offset and everything looks weird. This issue doesn't happen with normal ueberzug.

what it looks like (ueberzugpp with ranger)
![2023-05-13_00-19](https://github.com/jstkdng/ueberzugpp/assets/71287472/6dd0006d-fa1d-4c09-8657-e0bc99f72a02)

what it's supposed to look like (ueberzug with ranger)
![2023-05-13_00-20](https://github.com/jstkdng/ueberzugpp/assets/71287472/422b7d50-8ada-4b77-be25-edc3fbeb80f5)

**Comment by jstkdng** [comment]
thanks for reporting, I'll see what I can do.

**Comment by jstkdng** [comment]
please test master and check if the changes worked

**Comment by yarled-up** [comment]
> please test master and check if the changes worked

images display correctly on the 3 terminals i listed before, thanks!

**Comment by jstkdng** [comment]
alright then, closing
