### ISSUE TITLE
--no-stdin requires --pid-file

### ISSUE THREAD

**Issue by Arrow-x** [jstkdng/ueberzugpp#37]
it says to run --help but there is nothing there to help, test on `st` and `kitty`

**Comment by jstkdng** [comment]
hey, how are you running U++ with no-stdin?

**Comment by Arrow-x** [comment]
that is how the example script work? it creates the process captures in pid, creates a socket with that pid in the name, then later uses that to comunicate.
But I see that you have updated the script and it works so thanks!

**Comment by jstkdng** [comment]
yeah, the previous way worked but it wasn't able to detect available output methods. It should properly detect kitty/sixel this way now.
