### ISSUE TITLE
GSL at buildtime

### ISSUE THREAD

**Issue by sbradnick** [jstkdng/ueberzugpp#39]
Since automated build systems (generally) wouldn't reach out to the internet, this isn't working:

```
[   99s] [1/9] Creating directories for 'gsl-populate'
[   99s] [1/9] Performing download step (download, verify and extract) for 'gsl-populate'
[   99s]    dst='/home/abuild/rpmbuild/BUILD/ueberzugpp-2.8.2+git20230513.804060e/build/release/_deps/gsl-subbuild/gsl-populate-prefix/src/v4.0.0.tar.gz'
[   99s] -- Using src='https://github.com/microsoft/GSL/archive/refs/tags/v4.0.0.tar.gz'
[   99s] -- Using src='https://github.com/microsoft/GSL/archive/refs/tags/v4.0.0.tar.gz'
[   99s] -- Using src='https://github.com/microsoft/GSL/archive/refs/tags/v4.0.0.tar.gz'
[   99s] -- Using src='https://github.com/microsoft/GSL/archive/refs/tags/v4.0.0.tar.gz'
[   99s] -- Using src='https://github.com/microsoft/GSL/archive/refs/tags/v4.0.0.tar.gz'
[   99s] -- Using src='https://github.com/microsoft/GSL/archive/refs/tags/v4.0.0.tar.gz'
[   99s] CMake Error at gsl-subbuild/gsl-populate-prefix/src/gsl-populate-stamp/download-gsl-populate.cmake:170 (message):
[   99s]     error: downloading 'https://github.com/microsoft/GSL/archive/refs/tags/v4.0.0.tar.gz' failed
[   99s]           error: downloading 'https://github.com/microsoft/GSL/archive/refs/tags/v4.0.0.tar.gz' failed
[   99s]           error: downloading 'https://github.com/microsoft/GSL/archive/refs/tags/v4.0.0.tar.gz' failed
[   99s]           error: downloading 'https://github.com/microsoft/GSL/archive/refs/tags/v4.0.0.tar.gz' failed
[   99s]           error: downloading 'https://github.com/microsoft/GSL/archive/refs/tags/v4.0.0.tar.gz' failed
[   99s]           error: downloading 'https://github.com/microsoft/GSL/archive/refs/tags/v4.0.0.tar.gz' failed
[   99s] FAILED: gsl-populate-prefix/src/gsl-populate-stamp/gsl-populate-download /home/abuild/rpmbuild/BUILD/ueberzugpp-2.8.2+git20230513.804060e/build/release/_deps/gsl-subbuild/gsl-populate-prefix/src/gsl-populate-stamp/gsl-populate-download
[   99s] cd /home/abuild/rpmbuild/BUILD/ueberzugpp-2.8.2+git20230513.804060e/build/release/_deps && /usr/bin/cmake -P /home/abuild/rpmbuild/BUILD/ueberzugpp-2.8.2+git20230513.804060e/build/release/_deps/gsl-subbuild/gsl-populate-prefix/src/gsl-populate-stamp/download-gsl-populate.cmake && /usr/bin/cmake -P /home/abuild/rpmbuild/BUILD/ueberzugpp-2.8.2+git20230513.804060e/build/release/_deps/gsl-subbuild/gsl-populate-prefix/src/gsl-populate-stamp/verify-gsl-populate.cmake && /usr/bin/cmake -P /home/abuild/rpmbuild/BUILD/ueberzugpp-2.8.2+git20230513.804060e/build/release/_deps/gsl-subbuild/gsl-populate-prefix/src/gsl-populate-stamp/extract-gsl-populate.cmake && /usr/bin/cmake -E touch /home/abuild/rpmbuild/BUILD/ueberzugpp-2.8.2+git20230513.804060e/build/release/_deps/gsl-subbuild/gsl-populate-prefix/src/gsl-populate-stamp/gsl-populate-download
```

I'm not sure what this is and/or if it can be provided by an existing package.

Is there a flag to disable this or any more info on what it provides?

**Comment by jstkdng** [comment]
[GSL](https://github.com/microsoft/GSL) is a library to aid in following the C++ core guidlines. It can't be disabled.
does opensuse not have microsoft-gsl on their repos? that's a shame.
https://repology.org/project/ms-gsl/versions
Other's have implemented the package in the OBS it seems. https://build.opensuse.org/search?search_text=ms-gsl&search_for=0&name=1&attrib_type_id=

**Comment by sbradnick** [comment]
> does opensuse not have microsoft-gsl on their repos? that's a shame.

Wouldn't appear so. I've rolled my own (or rather, a copy of someone elses) into my home repo in OBS and I'll see if adding `cmake(Microsoft.GSL)` allows U++ to build again. If so, I'll close this out; if not - I'll probably have some more questions ;)

**Comment by jstkdng** [comment]
nice, hey do you mind if I add your obs repo to the README?

**Comment by sbradnick** [comment]
I'd rather it just be part of the distro overall, than based off my home. I haven't submitted it since the development was heavy enough (a good thing of course) and I didn't want to babysit it outside of my repo.

Looks like the original ueberzug was in "utilities" so U++ could go there; but would have to find a spot for `ms-gsl` as well and get that approved.

**Comment by jstkdng** [comment]
it'd be awesome if it became part of suse's repo :)

it's also weird that some of the ms-gsl projects in the OBS have a SUSE copyright header, is that standard for all spec files? or perhaps ms-gsl was removed for some reason.

**Comment by sbradnick** [comment]
> ... is that standard for all spec files?

Yes, when I do `vim ms-gsl.spec` the header is auto-populated.

> or perhaps ms-gsl was removed for some reason.

I have no idea really, but for openSUSE - if no one has wanted/needed it - it generally won't be there. _Maybe_ it exists in SUSE (SLES/SLED), I didn't check there - but that wouldn't specifically help here.

**Comment by sbradnick** [comment]
Looks like the resulting `ms-gsl-devel` which provides `cmake(Microsoft.GSL)` worked fine :+1:

I'll dig into finding somewhere for `ms-gsl` to live tomorrow and then hopefully get U++ into Tumbleweed.

**Comment by jstkdng** [comment]
awesome, thanks for the help. And good luck with your work.

**Comment by sbradnick** [comment]
happy to report that `ueberzugpp` is available in TW :+1:

```
$ zypper search --details --repo main-repository_oss --name ueberzugpp
Loading repository data...
Reading installed packages...

S | Name       | Type    | Version   | Arch   | Repository
--+------------+---------+-----------+--------+----------------------
v | ueberzugpp | package | 2.8.5-1.1 | x86_64 | Main Repository (OSS)
```

**Comment by jstkdng** [comment]
awesome man, ty for the help. I'll add that to the README. I think the package should have wayland support enabled though.

**Comment by sbradnick** [comment]
> I think the package should have wayland support enabled though.

I don't follow what that specifically means in the context of being available in "Main Repository (OSS)".

**Comment by jstkdng** [comment]
Shouldn't software in repositories have all features enabled?

**Comment by sbradnick** [comment]
> Shouldn't software in repositories have all features enabled?

Ah, ok - is that `-DENABLE_WLROOTS=ON`?

Just adding that causes:

```
[   15s] CMake Error at CMakeLists.txt:123 (find_package):
[   15s]   Could not find a package configuration file provided by "ECM" with any of
[   15s]   the following names:
[   15s]
[   15s]     ECMConfig.cmake
[   15s]     ecm-config.cmake
```

And it's hard to discern what it's looking for as nothing _seems_ to provides something akin to `cmake(ECMConfig)` or the like.

Maybe that's what these "Optional Dependencies" might provide:

* wayland (libwayland)
* wayland-protocols

but I haven't had luck with `pkgconfig(wayland-protocols)`. It's a valid "BuildRequires" but doesn't help w/ the problem.

Not sure if any of these might fit the bill:

```
$ zypper search --name libwayland
Loading repository data...
Reading installed packages...

S | Name                     | Summary                                     | Type
--+--------------------------+---------------------------------------------+--------
i | libwayland-client0       | Wayland core client library                 | package
  | libwayland-client0-32bit | Wayland core client library                 | package
i | libwayland-cursor0       | Wayland cursor library                      | package
  | libwayland-cursor0-32bit | Wayland cursor library                      | package
i | libwayland-egl1          | Additional egl functions for wayland        | package
  | libwayland-egl1-32bit    | Additional egl functions for wayland        | package
i | libwayland-server0       | Wayland core server library                 | package
  | libwayland-server0-32bit | Wayland core server library                 | package
  | libwaylandpp1            | Wayland C++ bindings                        | package
  | libwaylandpp1-debuginfo  | Debug information for package libwaylandpp1 | package
```

(the "i" here just means it's installed on my physical system - not necessarily in the build environment, but I don't use wayland [intentionally] myself in any way.)

**Comment by jstkdng** [comment]
yeah, it is extra-cmake-modules, it's in the README.

Are you in charge of maintining the package now? Should I direct all tumbleweed issues to you? :P

**Comment by sbradnick** [comment]
> Are you in charge of maintining the package now? Should I direct all tumbleweed issues to you? :P

Technically, yes.

Now I'm getting this:

```
[   15s] -- Could NOT find Wayland_Client (missing: Wayland_Client_LIBRARY Wayland_Client_INCLUDE_DIR) (found version "")
[   15s] CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
[   15s]   Could NOT find Wayland (missing: Wayland_LIBRARIES Client)
[   15s] Call Stack (most recent call first):
[   15s]   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
[   15s]   /usr/share/ECM/find-modules/FindWayland.cmake:110 (find_package_handle_standard_args)
[   15s]   CMakeLists.txt:127 (find_package)
```

And these don't seem to help:

```
BuildRequires:  pkgconfig(wayland-protocols)
BuildRequires:  libwayland-client0
```

Wayland seems ... fun.

**Comment by jstkdng** [comment]
>Now I'm getting this:

which packages provide `/usr/lib/pkgconfig/wayland-client.pc` and `/usr/lib/libwayland-client.so`?

>Wayland seems ... fun.

it is plenty fun I tell you

**Comment by sbradnick** [comment]
Adding these 2 seems to make it happy:

```
BuildRequires:  pkgconfig(wayland-protocols)
BuildRequires:  pkgconfig(wayland-client)
```

In hindsight, it seems so obvious :P

These changes will be included when I push 2.8.6 up to openSUSE:Factory:

```
Index: ueberzugpp.spec
===================================================================
--- ueberzugpp.spec     (revision 30)
+++ ueberzugpp.spec     (working copy)
@@ -28,6 +28,7 @@
 BuildRequires:  cmake
 BuildRequires:  cmake(Microsoft.GSL)
 BuildRequires:  cmake(spdlog)
+BuildRequires:  extra-cmake-modules
 BuildRequires:  gcc-c++
 BuildRequires:  git-core
 BuildRequires:  make
@@ -40,6 +41,8 @@
 BuildRequires:  pkgconfig(opencv4)
 BuildRequires:  pkgconfig(tbb)
 BuildRequires:  pkgconfig(vips)
+BuildRequires:  pkgconfig(wayland-client)
+BuildRequires:  pkgconfig(wayland-protocols)
 BuildRequires:  pkgconfig(xcb-image)

 %description
@@ -65,7 +68,7 @@
 %autosetup

 %build
-%cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_SKIP_RPATH=YES -DCMAKE_BUILD_TYPE=release
+%cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_SKIP_RPATH=YES -DCMAKE_BUILD_TYPE=release -DENABLE_WLROOTS=ON
 %cmake_build

 %install
```

**Comment by jstkdng** [comment]
Can the spec file also be used for fedora? Or will the package names change between them.

**Comment by sbradnick** [comment]
No clue, I exclusively use openSUSE. OBS can build against various Fedora versions and I know logic can be put in place to use different `BuildRequires` based off OS types, so there really isn't anything stopping OBS from producing Fedora-centric RPMs other than someone validating what Fedora names their equivalent libraries.

**Comment by jstkdng** [comment]
I see, I'll try to use opensuse's spec file for fedora support. Thanks again man.
