### ISSUE TITLE
Issue with tmux when replacing ueberzug with ueberzugpp

### ISSUE THREAD

**Issue by krivahtoo** [jstkdng/ueberzugpp#40]
I tried replacing ueberzug with ueberzugpp, and every other program (e.g. ranger, ncmpcpp-ueberzug) is working as expected, but tmux is displaying messages in only two windows blocking the windows. When switching back to ueberzug the messages disappears.

![2023-05-15-104247_648x392_scrot](https://github.com/jstkdng/ueberzugpp/assets/41364823/7270b5f7-4585-4235-91a6-99862ef410a4)

Os: `Arch 6.1.26-1-lts`
tmux: `3.3a`
ueberzugpp: `2.8.2`

**Comment by jstkdng** [comment]
hey, that's because ueberzug registers its own tmux hooks at runtime. If you use OG ueberzug whilst you are in tmux then that issue will appear. Doesn't closing the tmux session fix the issue?

**Comment by krivahtoo** [comment]
Thanks for the quick reply.

> If you use OG ueberzug whilst you are in tmux then that issue will appear.

Okay, that makes sense.

> Doesn't closing the tmux session fix the issue?

Probably, I only closed the affected windows. I guess this means the affected windows had OG ueberzug hooks at some point.

**Comment by jstkdng** [comment]
The hooks affect the whole session, not just a subset of windows. Closing the tmux session should clear the old hooks.
