### ISSUE TITLE
fzfub not working on MacOS

### ISSUE THREAD

**Issue by justchokingaround** [jstkdng/ueberzugpp#41]
in the example fzfub script, the following error shows up when running it:
```sh
The following arguments were not expected: /tmp/.97473D95-EBC3-48D1-82BA-E35BB1BFF4CF --pid-file
```
this is on version 2.8.0 of ueberzugpp, installed with homebrew

**Comment by jstkdng** [comment]
update to 2.8.2

**Comment by justchokingaround** [comment]
<img width="907" alt="image" src="https://github.com/jstkdng/ueberzugpp/assets/44473782/40aed137-7eb1-4c01-b1f0-840a5c060a05">

the latest homebrew version is 2.8.0, should i try compiling from source?

**Comment by jstkdng** [comment]
ueberzugpp is not yet in homebrew, you have to download the formula here https://github.com/jstkdng/ueberzugpp/blob/master/homebrew/ueberzugpp.rb and install the new version

**Comment by justchokingaround** [comment]
```
Last 15 lines from /Users/chomsky/Library/Logs/Homebrew/ueberzugpp/02.cmake:
/tmp/ueberzugpp-20230515-60031-161wzsr/ueberzugpp-2.8.2/src/terminal.cpp:156:34: error: implicit instantiation of undefined template 'std::array<pollfd, 1>'
    std::array<struct pollfd, 1> input;
                                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1/__tuple:219:64: note: template is declared here
template <class _Tp, size_t _Size> struct _LIBCPP_TEMPLATE_VIS array;
                                                               ^
...

1 error generated.
make[2]: *** [CMakeFiles/ueberzug.dir/src/terminal.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/ueberzug.dir/all] Error 2
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/homebrew-core!
```
i am getting this error when trying to brew install from the latest homebrew script (sorry i forgot it's not in homebrew-core)

**Comment by jstkdng** [comment]
now that's something weird, I'll see what I can do.

**Comment by jstkdng** [comment]
2.8.3 should be available now

**Comment by jstkdng** [comment]
It compiles on macos now. Closing.
