### ISSUE TITLE
Trying to install fedora while tbb is already installed gives an error

### ISSUE THREAD

**Issue by TahaUNAL** [jstkdng/ueberzugpp#42]
Trying to build gives the following error on me. I am using fedora 37. I don't know anything about building a C package. Sorry if that's a simple error to fix. i just wanted to share the error i got so that it will be helpful for beginners who are getting similar errors as me.

```
  CMake Error at CMakeLists.txt:39 (find_package):
  By not providing "FindTBB.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "TBB", but
  CMake did not find one.

  Could not find a package configuration file provided by "TBB" with any of
  the following names:

    TBBConfig.cmake
    tbb-config.cmake

  Add the installation prefix of "TBB" to CMAKE_PREFIX_PATH or set "TBB_DIR"
  to a directory containing one of the above files.  If "TBB" provides a
  separate development package or SDK, be sure it has been installed. 
```

**Comment by jstkdng** [comment]
can you list the files that tbb provides? like

`rpm list tbb | grep cmake`

and also, I think in fedora you have to install tbb-devel in order to get the required files.

**Comment by jstkdng** [comment]
if you still have issues we can continue the discussion, closing for now.
