### ISSUE TITLE
support swayimg

### ISSUE THREAD

**Issue by Arrow-x** [jstkdng/ueberzugpp#43]
[swayimg](https://github.com/artemsen/swayimg)  has support for SwayWM and Hyperland, it works somewhat like an Xorg borderless window (even though you can still select it and move it about), ytfzf already support it, it can help support Tmux on Wayland

**Comment by jstkdng** [comment]
hey, thanks for the suggestion.

Can the swayimg window be moved around? does it always spawn fullscreen?

**Comment by Arrow-x** [comment]
yes it can be moved around, no it doesn't open full screen (unless you want it to)

**Comment by jstkdng** [comment]
I'll see what I can do

**Comment by jstkdng** [comment]
It was an interesting experience adding support for sway but now it works. It still needs some polishing though. Please do test it, your bar has to be on the bottom though.

**Comment by Arrow-x** [comment]
starting upp with `ueberzugpp layer --no-stdin --silent --output sway --pid-file "$UB_PID_FILE"` (like the fzf script included) will fall back the chefa, tested on `foot` `st` (under xwayland) and `kitty`

**Comment by jstkdng** [comment]
hey, try setting the output in U++'s config file

**Comment by Arrow-x** [comment]
where is that exactly; since it's not created by default and no mention of in the help

**Comment by jstkdng** [comment]
It is in the README.md. It should be located in `~/.config/ueberzugpp/config.json`

**Comment by jstkdng** [comment]
hmm, did you compile with sway support? You need to add `-DENABLE_SWAY=ON` to the compilation flags.

**Comment by Arrow-x** [comment]
`cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_SWAY=ON ..` gives me this error
```
CMake Error at CMakeLists.txt:132 (find_package):
  Could not find a package configuration file provided by "ECM" with any of
  the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
```

**Comment by jstkdng** [comment]
Install `extra-cmake-modules` on your distro.

**Comment by jstkdng** [comment]
I don't know if that's possible, would need the ask some wayland pro for that. (or maybe the sway developers)

**Comment by Arrow-x** [comment]
this is excellent though, can finally use tmux on wayland

**Comment by jstkdng** [comment]
yeah it kinda works, tmux event's don't work though.

**Comment by jstkdng** [comment]
>'ueberzug tmux window-layout-changed 426441' returned 127

thats weird, unless you also have OG ueberzug installed it should never fail.

>it also doesn't remove the preview when moving between tmux windows

also weird, works on my machine

**Comment by jstkdng** [comment]
Check your path, maybe og ueberzug is still installed somewhere (like pip idk). Otherwise, I changed master so hooks only call ueberzugpp. Restart your tmux session and test it out.

**Comment by Arrow-x** [comment]
yep that fixes it ( I linked the bin to uebersugpp by hand and didn't use the install since it doesn't create a ueberzugpp bin that all my scripts call to)
it still doesn't respect sway lay out though (the tabbed one moving between them doesn't hide the layer) and also workspaces, moving the terminal doesn't take the ueberzug layer with it

**Comment by jstkdng** [comment]
all those issues are due to the image just being a separate floating window. This method of display is really limited.

**Comment by jstkdng** [comment]
latest release should have proper sway support. If any problems arise open a new issue.

**Comment by Arrow-x** [comment]
the positioning is still off too high when the bar is on the top?

**Comment by jstkdng** [comment]
I'm gonna have to research that, if you can help that'd be awesome. So it'll have to wait.
