### ISSUE TITLE
v2.8.5 and input processing

### ISSUE THREAD

**Issue by xaizek** [jstkdng/ueberzugpp#47]
Fewer dependencies is nice, but...

v2.8.4:
```
ueberzug layer < /dev/null
# ueberzugpp exits
```
v2.8.5:
```
ueberzug layer < /dev/null
# ueberzugpp consumes 100% of a CPU
```

Also first command sent to `stdin` seems to be ignored, but I don't know if that's related, might be a separate issue.  The issue with the hang is that if `stdin` source is closed or has nothing, `ueberzug` still tries to read from it.

**Comment by xaizek** [comment]
Hi.

The the actual case is that of connecting `stdin` to a pipe which is then closed when app exits, this caused `ueberzugpp` to finish as well.

Logs on the second issue.

v2.8.4:
```
 _    _      _
| |  | |    | |                                _     _
| |  | | ___| |__   ___ _ __ _____   _  __ _ _| |_ _| |_
| |  | |/ _ \ '_ \ / _ \ '__|_  / | | |/ _` |_   _|_   _|
| |__| |  __/ |_) |  __/ |   / /| |_| | (_| | |_|   |_|
 \____/ \___|_.__/ \___|_|  /___|\__,_|\__, |
                                        __/ |
                                       |___/     v2.8.4
[2023-05-26 14:39:59.112] [terminal] [info] TERM="tmux-256color", TERM_PROGRAM="tmux"
[2023-05-26 14:39:59.123] [X11] [info] Canvas created
[2023-05-26 14:39:59.152] [main] [info] Listening for commands on socket /tmp/ueberzugpp-23668.socket.
[2023-05-26 14:39:59.164] [main] [info] Command received: {"action":"add","height":64,"identifier":"vifm-preview","path":"/home/xaizek/downloads/kermlin1.jpg","width":117,"x":121,"y":2}
[2023-05-26 14:39:59.176] [opencv] [info] Loading image /home/xaizek/.cache/ueberzugpp/7446ef9072b6848f698c7ac33d677d839eb122b42547fa157500173ad71ac7251aa87d94037e9a653f02943b9aed823a10fbd3351b58405a1d94a781269d3912.jpg
[2023-05-26 14:39:59.212] [main] [info] Command received: {"action":"remove","identifier":"vifm-preview"}
[2023-05-26 14:39:59.212] [main] [info] Removing image.
[2023-05-26 14:39:59.213] [main] [info] Command received: {"action":"add","height":64,"identifier":"vifm-preview","path":"/home/xaizek/downloads/kermlin1.jpg","width":117,"x":121,"y":2}
[2023-05-26 14:39:59.223] [opencv] [info] Loading image /home/xaizek/.cache/ueberzugpp/7446ef9072b6848f698c7ac33d677d839eb122b42547fa157500173ad71ac7251aa87d94037e9a653f02943b9aed823a10fbd3351b58405a1d94a781269d3912.jpg
[2023-05-26 14:39:59.534] [main] [info] Command received: {"action":"remove","identifier":"vifm-preview"}
[2023-05-26 14:39:59.534] [main] [info] Removing image.
[2023-05-26 14:40:00.044] [main] [info] Command received: {"action":"tmux","hook":"session-window-changed"}
```

v2.8.5:
```
 _    _      _
| |  | |    | |                                _     _
| |  | | ___| |__   ___ _ __ _____   _  __ _ _| |_ _| |_
| |  | |/ _ \ '_ \ / _ \ '__|_  / | | |/ _` |_   _|_   _|
| |__| |  __/ |_) |  __/ |   / /| |_| | (_| | |_|   |_|
 \____/ \___|_.__/ \___|_|  /___|\__,_|\__, |
                                        __/ |
                                       |___/     v2.8.5
[2023-05-26 14:39:27.777] [terminal] [info] TERM="tmux-256color", TERM_PROGRAM="tmux"
[2023-05-26 14:39:27.787] [X11] [info] Canvas created
[2023-05-26 14:39:27.817] [main] [info] Listening for commands on socket /tmp/ueberzugpp-23320.socket.
[2023-05-26 14:39:27.828] [main] [error] There was an error parsing the command.
[2023-05-26 14:39:28.470] [main] [info] Command received: {"action":"remove","identifier":"vifm-preview"}
[2023-05-26 14:39:28.470] [main] [info] Removing image.
[2023-05-26 14:39:57.128] [main] [error] SIGTERM received, exiting.
[2023-05-26 14:39:57.163] [main] [info] Exiting ueberzugpp.
```

I can debug this further later if you don't see anything obvious.

I'm using it in Vifm through [this plugin](https://github.com/vifm/vifm/blob/master/data/plugins/ueberzug/init.lua).

**Comment by jstkdng** [comment]
Ah yes I can see, I switched to non blocking I/O on 2.8.5 and it seems it's broken in this particular case. I've commited a fix, please test it. I'll check that second issue of yours.

**Comment by jstkdng** [comment]
I see vifm has a plugin for ueberzug, how are you supposed to configure it? is it better than vifmimg?

**Comment by xaizek** [comment]
Thanks, will try the fix soon.

You can see plugin instructions [on the wiki](https://wiki.vifm.info/index.php/Using_Lua_plugins#Installation). Basically, put that file in `plugins/ueberzug/init.lua` next to `vifmrc` (just do `:cd $VIFM` inside Vifm) and add to configuration something like:
```vim
    :fileviewer {*.png}
              \ #ueberzug#view %px %py %pw %ph
              \ %pc
              \ #ueberzug#clear
```

The plugin doesn't handle any extra file types like PDFs and others at the moment, but I think this way to use ueberzug is better because you can start it on demand only when it's necessary after running `vifm` as usual and not through a wrapper script which launches previewer even when it's not needed.  ueberzug's process even visible in `:jobs` and can be killed if desired and the plugin will handle it well.

**Comment by xaizek** [comment]
Thank you, I can confirm that `ueberzug` doesn't hang on 81b737c8c84aed625ec9ce742784b04ff3c5920c.  We can consider this issue done if you wish.

Regarding the second issue (for which another GitHub issue can be opened), I've added failed command to the log and looks like this:
```
[2023-05-26 17:50:06.653] [main] [error] There was an error parsing the command: { "action":"add", "identifier":"vifm-preview",  "x":61, "y":2, "width":57, "height":17,  "path":"/home/xaizek/downloads/a.jpg"}
{"action":"remove", "identifier":"vifm-preview"}
{ "action":"add", "identifier":"vifm-preview",  "x":61, "y":2, "width":57, "height":17,  "path":"/home/xaizek/downloads/a.jpg"}
{"action":"remove", "identifier":"vifm-preview"}
{ "action":"add", "identifier":"vifm-preview",  "x":61, "y":2, "width":57, "height":17,  "path":"/home/xaizek/downloads/a.jpg"}
```

In other words, `ueberzugpp` can read more than one command at a time, but can't handle it.

**Comment by jstkdng** [comment]
hmmm, I think it is because vifm (or the kernel?) is flushing both commands at the same time, combining them into `{cmd1}\n{cmd2}\n` and ueberzug reading them wrong.

**Comment by xaizek** [comment]
With pipes there are no borders between "messages", they need to be enforced by applications.  In this case, ueberzug should probably collect read data into a buffer, process full lines and leave unread data in the buffer to be used after receiving `\n`. That's basically what `std::getline(std::cin)` was doing for you until e0cc012.

**Comment by jstkdng** [comment]
indeed, but getline blocks. Should be fixed on master now, not sure if it is slower or faster though.

**Comment by xaizek** [comment]
Yes, 0cdc00c2969e3762b2c798048992852b0853352c fixes the second issue. Thanks!

Doing 100-200 syscalls is slower than doing 1-3, but one would have to measure it to notice any difference.

**Comment by jstkdng** [comment]
Hi again, I noticed that the ueberzug plugin breaks kitty, sixel and iterm2's output. Is this an issue on vifm's side?

**Comment by xaizek** [comment]
Hi.  It was meant to be used with X11 output.  If `ueberzugpp` just prints escape sequences (unlike kitty's implementation which interacts with the terminal), it should be possible to write a version with the use of socket interface for which kitty, sixel and iterm2 canvases work (should be combined with [`%pd`](https://vifm.info/vimdoc.shtml#vifm-%25pd) in `:fileviewer` command).  This constraint is due to detachment of background jobs from the terminal so they won't mess it up (also job communication is read-only, write-only or none).

**Comment by jstkdng** [comment]
Both kitty and iterm2 also have to use escape codes to comunicate with the terminal. But I see your point.

**Comment by xaizek** [comment]
At least iterm2 protocol doesn't *read* anything from the terminal and doesn't check that it's connected to it as far as I know.  And I don't see anything like that in your implementation for kitty.  Detachment from tty prevents doing `ioctl()` on a terminal file description or writing something to a terminal and expecting it to provide a response.  Preparing a buffer full of escape sequences to be fed into a terminal should work if that's the whole communication.

**Comment by jstkdng** [comment]
>And I don't see anything like that in your implementation for kitty

all the `ioctl`-ing is done before the canvas is created

>Preparing a buffer full of escape sequences to be fed into a terminal should work if that's the whole communication.

for some reason it currently doesn't. I believe latest kitty is also broken in vifm? or was that issue fixed.

I kinda had this same issue with ctpv so in the end I have to use scripts that spawn and use an external U++ instance on terminal file managers. Ranger is a particular case as all canvases works without an external script, it is still slow than vifm or lf though.

**Comment by xaizek** [comment]
> all the `ioctl`-ing is done before the canvas is created

Then starting background job might need a flag to stay connected to the terminal.  Although the plugin can probably work through socket even now if `vifm.run('ueberzug ... %N')` is used.  I might try making a separate one specifically for `ueberzugpp`.

I actually think that window overlay is a superior way of displaying images in terminals compared to sixel or terminal-specific interfaces, because overlay is reliable unlike any other solution which tries to turn terminal into rich text processor.

> for some reason it currently doesn't.

In current form the plugin doesn't even read standard output of `ueberzugpp` and connects it to `/dev/null`.

> I believe latest kitty is also broken in vifm? or was that issue fixed.

This should work in v0.13: https://github.com/vifm/vifm/issues/731#issuecomment-1445124018

**Comment by xaizek** [comment]
> if you don't want to interact with sockets directly you can just use the U++ binary to send commands to another U++ instance

`cmd` subcommand was useful.  I've adjusted the plugin but non-overlay backends still won't work.  U++ prints directly to a terminal which doesn't play well with TUI, but even if I capture output stream there is no way to wait for end of an image.  Normally end is found on hitting eof-of-file and in this case `cmd` could provide output by printing it but implementing this is probably not worth the effort.

**Comment by jstkdng** [comment]
>non-overlay backends still won't work

I see, that's a shame.

>but implementing this is probably not worth the effort.

yeah, it'd be really hard and it wouldn't work with animated pictures. I guess that's what `vifmimg` is good for.
