### ISSUE TITLE
feat: debian and ubuntu packages

### ISSUE THREAD

**Issue by justchokingaround** [jstkdng/ueberzugpp#48]
can we get a package for debian and ubuntu please?
if you don't want to deal with this, i could make those myself if that's alright, however i have no experience with creating packages for those distributions

**Comment by jstkdng** [comment]
>Debian 11 is missing a dependency.

I have tested compilation on debian 11 and it works. What dependency are you refering to?

**Comment by jstkdng** [comment]
I've made a repository for debian and ubuntu. Debian 10 wasn't possible to build as it needs buster-backports and that is not available on the OBS afaik.

https://software.opensuse.org//download.html?project=home%3Ajustkidding&package=ueberzugpp

**Comment by jstkdng** [comment]
Hey, don't blame me, I didn't make the UI of that site. As long as it works it should be fine.

**Comment by jstkdng** [comment]
alright then, debian package works.

**Comment by jstkdng** [comment]
yeah, that will take some time to be supported by the platform I'm using to build.
