### ISSUE TITLE
Waybar interferes with sway positioning

### ISSUE THREAD

**Issue by Euro20179** [jstkdng/ueberzugpp#49]
without waybar open
![x](https://github.com/jstkdng/ueberzugpp/assets/56898436/8d0e640b-9637-4a16-92d6-caed9141a818)

with waybar open
![x2](https://github.com/jstkdng/ueberzugpp/assets/56898436/b3ad951c-e1ad-44c3-847e-fc3a76e497c8)

ueberzugpp version: 2.8.5 (ueberzugpp package from aur)

my waybar height is 30

**Comment by jstkdng** [comment]
hi, is your waybar on the top or the bottom of the screen?

**Comment by Euro20179** [comment]
> hi, is your waybar on the top or the bottom of the screen?

yes

**Comment by jstkdng** [comment]
Yeah, the sway canvas needs some polishing regarding positioning. I'll keep this issue open for tracking this.

**Comment by jstkdng** [comment]
I've added a fix to master, please test it.

**Comment by Euro20179** [comment]
I dont think this has anything to do with your last commit but, when i use -o sway, it uses chafa.

**Comment by jstkdng** [comment]
hmm, maybe you disabled sway support last compilation?

**Comment by jstkdng** [comment]
alright, latest commit should make sway's positioning on par with x11's positioning. Closing.
