### ISSUE TITLE
error when building on fedora 38

### ISSUE THREAD

**Issue by adetabrani** [jstkdng/ueberzugpp#50]
![1685108133_May26_20:35:33](https://github.com/jstkdng/ueberzugpp/assets/47938004/10a4bb43-ffd9-47e6-be0f-a46a54c892e1)

I just pulled to the latest version, but I can't build U++, I've also made sure all package dependencies are installed.

**Comment by jstkdng** [comment]
Hi, is there a package called util-linux-libs? If not, try to check which package provides a file called `uuid.pc`.

I guess not all distros package this.

**Comment by adetabrani** [comment]
where is that file located?

**Comment by jstkdng** [comment]
In arch it is located under `/usr/lib/pkgconfig/uuid.pc`

**Comment by adetabrani** [comment]
![1685111683_May26_21:34:43](https://github.com/jstkdng/ueberzugpp/assets/47938004/dfa79711-cb44-4791-b406-e9a572486461)

i didn't find it, just found this file,

in the fedora package found only util-linux (I'm not sure if this is the package you mean) and it's installed by default, even I've installed the packages uuid-c++ and uuid-dce, but still can't build

**Comment by jstkdng** [comment]
I found the package providing this dependency, it is called libuuid

**Comment by jstkdng** [comment]
I ended up removing the uuid dependency, should be working now.

**Comment by adetabrani** [comment]
thanks, but now I have a problem with the integration of the script on lf, I'm still using the lf script for ueberzug original and it works, but recently after I upgraded to version u++ I encountered a bug, the preview image is  doesn't disappear when i exit lf.

I tried to use the script that you have made but it doesn't work in my device, preview image does not appear at all

**Comment by jstkdng** [comment]
can you try compiling from master?

**Comment by adetabrani** [comment]
I got this bug after compiling from master
