### ISSUE TITLE
[bug] ueberzugpp probable synchronisation issue on slow machine

### ISSUE THREAD

**Issue by ghost** [jstkdng/ueberzugpp#54]
works fine with the old ueberzug method. But it quickly brakes  with the new ueberzugpp method. Tested on Debian 11 64bits.

```
+ choice=
+ ueberzugpp cmd -s /tmp/ueberzugpp-21889.socket -a exit
terminate called after throwing an instance of 'std::system_error'
  what():  Connection refused
Aborted
```

the config bypasses the issue.

```
{
    "layer": {
        "no-opencv":true
    }
}
```

**Comment by jstkdng** [comment]
That coredump seems different from the first one, can you check `ueberzugpp` has crashed more than once? Just run `coredumpctl | grep ueberzug`

**Comment by jstkdng** [comment]
I think I fixed the second issue you sent, it was indeed related to slow machines ,or rather, sending a lot of commands really fast, even on my PC it would crash, and it is a 5950X.
