### ISSUE TITLE
help wanted: simplest way to display an image using ueberzugpp

### ISSUE THREAD

**Issue by justchokingaround** [jstkdng/ueberzugpp#56]
i would like to get some help on how i could simply display an image in the terminal, by specifying its position, something that was done in Luke Smith's video using the original ueberzug:

![image](https://github.com/jstkdng/ueberzugpp/assets/44473782/dec0d574-4df7-487d-8e09-7deb1e4f3544)

```bash
#!/bin/bash
source "`ueberzug library`"

ImageLayer 0< <(
  ImageLayer::add [identifier]="example0" [x]="$2" [y]="$3" [max_width]="$5" [max_height]="$4" [path]="$1"
  read
)

```

**Comment by jstkdng** [comment]
hm, that bash library was later deprecated by seebye so I wouldn't use it. The easiest way to display images is through the unix socket `ueberzugpp` provides, be it with another tool or with `ueberzugpp` itself.Plus it is not so "simple", `ueberzug` still has to keep running to handle X11 events. I was thinking of implementing a standalone version of ueberzug but that'd only work with kitty, sixel and iterm2, plus it would not work with animated gifs.

**Comment by justchokingaround** [comment]
and how could i do that with a shell script to just display the image, with `ueberzugpp` itself? i've been struggling a bit to figure out how everything works, and it's hard to find any documentation online

**Comment by jstkdng** [comment]
The `lfub` script and the `fzfub` script are examples of that. Unless you want something easier than that.

**Comment by justchokingaround** [comment]
actually, i just figured out how to replicate that, this is what i was trying to achieve:
```sh
#!/bin/sh

UB_PID_FILE="/tmp/.$(uuidgen)"
ueberzugpp layer --no-stdin --silent --use-escape-codes --pid-file "$UB_PID_FILE"
UB_PID="$(cat "$UB_PID_FILE")"
export UB_SOCKET=/tmp/ueberzugpp-"$UB_PID".socket
ueberzugpp cmd -s "$UB_SOCKET" -a add -i PREVIEW -x "$1" -y "$2" --max-width "$3" --max-height "$4" -f "$5"
read -r
ueberzugpp cmd -s "$UB_SOCKET" -a exit
```

![image](https://github.com/jstkdng/ueberzugpp/assets/44473782/84888253-7a2c-44d5-9541-22ff3b213ca8)


should i PR it as an example in the scripts directory? it might be useful to some people i guess

**Comment by jstkdng** [comment]
sure, it could be useful to someone else.

**Comment by justchokingaround** [comment]
using this with the output set to `wayland` doesn't work btw, i'm not sure if i should report that or not?

**Comment by jstkdng** [comment]
no need, there's already #55 .
