### ISSUE TITLE
[help] cannot get lf image preview working on wayland

### ISSUE THREAD

**Issue by justchokingaround** [jstkdng/ueberzugpp#57]
i am trying to setup image preview in lf using ueberzugpp on wayland, however i cannot get it to work. i copied all the 3 files in the `lf` directory provided by this repository: cleaner, previewer and lfub, however images just don't show up (other previews seem to work fine)

this is my lfrc:
```
set previewer ~/.config/lf/preview
set cleaner ~/.config/lf/cleaner
set drawbox
```
i am not sure what to try next

**Comment by jstkdng** [comment]
The config is fine, plus,  you need to run the `lfub` script, not only lf. I'd place the script in some directory in your `PATH`.

**Comment by justchokingaround** [comment]
i didn't realize you have to run `lfub` instead of `lf` for it to work, my bad
