### ISSUE TITLE
ueberzugpp doesn't places the images on correct position when the terminal is resized on hyprland

### ISSUE THREAD

**Issue by swaroopanand10** [jstkdng/ueberzugpp#58]
I am using Hyprland with kitty and lf (with integration script given by you), Ueberzugpp(aur version) seems to display images fine in normal terminal size, but whenever I open another terminal in tiling on the side of current terminal the image misplaces itself.
![image](https://github.com/jstkdng/ueberzugpp/assets/42596780/44d79071-da45-45bb-9e79-91ee8a46cdd9)
as you can see in the image the as soon as the new terminal(empty terminal on the left) is opened the image misplaced itself to some weird location instead of staying on its correct place in the right terminal with lf.

this also happens whenever I switch to floating mode of terminal or try to resize the terminal in anyway and it happens in all of the terminals ( I also tried it in foot and alacritty)
This does not happens in xorg window managers like bspwm.

**Comment by jstkdng** [comment]
>this also happens whenever I switch to floating mode of terminal or try to resize the terminal in anyway and it happens in

yes, that is expected behavior, as the image is just a floating window independent of the terminal (you can move it around if you try). Under X11, the image window is a child of the terminal so it moves around with it.

>as you can see in the image the as soon as the new terminal(empty terminal on the left) is opened the image misplaced itself to some weird location instead of staying on its correct place in the right terminal with lf.

that is not expected, I'll see what I can do.

**Comment by jstkdng** [comment]
I have updated the code on master, it should fix this issue.

**Comment by swaroopanand10** [comment]
thanks, it works, and now the images are placed at proper places, 
but there is only one issue that scrolling through a large number of images continously at speed sometimes does cause them to not appear at all. 
But this happens only sometimes and not all the times, so maybe this is some other performance issue on my end.
very much thanks for fixing the issue.

**Comment by jstkdng** [comment]
as long as `ueberzugpp` doesn't crash then it should be fine. You can check if it crashed with the `coredumpctl` command.
