### ISSUE TITLE
[bug] black image

### ISSUE THREAD

**Issue by pirate486743186** [jstkdng/ueberzugpp#60]
In ueberzug with the old method (ranger), this image is black. Looks fine in image viewer.

With both the official Debian 11 deb and the one i compiled.

![0017](https://github.com/jstkdng/ueberzugpp/assets/429925/d79126af-a0b8-4e73-bd93-a425f43f0629)

**Comment by jstkdng** [comment]
Oh yeah, opencv strugges sometimes, libvips works fine. I've updated the code for opencv on master.
