### ISSUE TITLE
[feature] close ueberzugpp windows

### ISSUE THREAD

**Issue by pirate486743186** [jstkdng/ueberzugpp#61]
Terminals can do various strange things that ueberzugpp can't detect. Like tabs, or splitting tabs in new windows etc.... Then you are left with a ueberzugpp window floating at some odd place.

It would be nice, if we could close ueberzugpp window with an optional little red X on a corner.

**Comment by jstkdng** [comment]
Sorry, I don't have that planned, it would increase the complexity quite a bit. If you want tabs/splitting windows I'd recommend using tmux which is actually supported.

**Comment by jstkdng** [comment]
and you said it correctly, there's no way for `ueberzugpp` to know when terminals do this. Tmux is kind enough to provide hooks that `ueberzugpp` can respond to whenever a new tab is created or the windows are split. To provide a way to remove an image with your cursor click would increase complexity and I'm not willing to tackle that at the moment.

**Comment by jstkdng** [comment]
That's most likely the file manager responding to the clicks inside/outside the terminal.
