### ISSUE TITLE
how should i config to use windows terminal with wsl2?

### ISSUE THREAD

**Issue by yuzhegan** [jstkdng/ueberzugpp#62]
how should i config to use windows terminal with wsl2? my wslg is archlinux ,i had "yay -S install  ueberzugpp "
but  can not preivew my image in ranger  when i set "set preview_images true,
set preview_images_method ueberzug" , any alse should i to set? 
error
"terminate called after throwing an instance of 'std::runtime_error'
  what():  UNABLE TO CALCULATE TERMINAL SIZES
fish: Job 1, 'ueberzugpp layer' terminated by signal SIGABRT (Abort)"
when i cod " ueberzugpp layer"

**Comment by jstkdng** [comment]
Hi, thanks for reporting. Which terminal are you using? I think the windows terminal doesn't implement the methos `ueberzugpp` uses to calculate the terminal sizes. Can you test WezTerm? It should work when you run `ueberzugpp layer`.

**Comment by yuzhegan** [comment]
i had just use WezTerm,and use the [test scripts](https://github.com/jstkdng/ueberzugpp/issues/56), 
```sh
#!/bin/sh

UB_PID_FILE="/tmp/.$(uuidgen)"
ueberzugpp layer --no-stdin --silent --use-escape-codes --pid-file "$UB_PID_FILE"
UB_PID="$(cat "$UB_PID_FILE")"
export UB_SOCKET=/tmp/ueberzugpp-"$UB_PID".socket
ueberzugpp cmd -s "$UB_SOCKET" -a add -i PREVIEW -x "$1" -y "$2" --max-width "$3" --max-height "$4" -f "$5"
read -r
ueberzugpp cmd -s "$UB_SOCKET" -a exit
```
then i paste the "sh ueberzug.sh 0 30 30 ./domo.png" it show nothing in the terminal.

this is my config:

```
{
    "layer": {
        "silent": true,
        "use-escape-codes": false,
        "no-stdin": false,
        "output": "sixel"
    }
}
```
OS: WSLg  archlinux
terminal: WezTerm

but when i change the config: "output":"item2", it can show the pic, but this picture is not clear.
how should i do to use the ueberzugpp?
thanks for your replay

**Comment by yuzhegan** [comment]
kitty also can't output anything

**Comment by yuzhegan** [comment]
does this suppter alaclitty in windwos?

**Comment by jstkdng** [comment]
Hmm, that script needs 5 arguments but you are passing 4. If that doesn't work then open an issue with wezterm. 

>does this suppter alaclitty in windwos?

alacritty could work, you need a patched version though. https://github.com/chrhasse/alacritty-sixel

**Comment by jstkdng** [comment]
sorry, didn't see your comment. That config is fine.

**Comment by jstkdng** [comment]
no word from op for some time now, closing
