### ISSUE TITLE
[bug] socket implementation slow on slow machine

### ISSUE THREAD

**Issue by pirate486743186** [jstkdng/ueberzugpp#63]
in ranger, it's reasonably fast.
in lobster, it's annoyingly slower and it seams to be fine on a fast machine.
most likely, it's a bug in ueberzugpp

This could be a cousin of the previous bug. An other synchronization issue. #54

**Comment by jstkdng** [comment]
Can you test `lfub` and check if the socket issue is still there? Could be an issue with lobster.

**Comment by jstkdng** [comment]
Follow the instructions of #57

**Comment by jstkdng** [comment]
You don't need to be on wayland for it to work. Just copy preview and cleaner to ~/.config/lf and edit the file lfrc with the following content:

```
set previewer ~/.config/lf/preview
set cleaner ~/.config/lf/cleaner
set drawbox
```

after that just run `lfub`

**Comment by jstkdng** [comment]
They are here. https://github.com/jstkdng/ueberzugpp/tree/master/scripts/lf

I should add them to the binaries.

**Comment by jstkdng** [comment]
Hmm, is it slow even when using libvips only?

**Comment by jstkdng** [comment]
I've made some performance improvements with the X11 output. If that doesn't help then maybe it could be an issue with your kernel? Perhaps the kernel from debian 11 doesn't perform well  when a lot of system calls happen in a short period of time.

**Comment by jstkdng** [comment]
I don't think so, all synchronization issues have been fixed on X11. Otherwise, sending fast commands would just crash `ueberzugpp`. Maybe the culprit is that debian 11's gcc compiler doesn't output performant enough binaries. If you have the same problem on debian 12 do reopen this issue.

**Comment by jstkdng** [comment]
Hmm, I'll see what I can do.

**Comment by jstkdng** [comment]
I've made some changes, the socket should be faster now.

**Comment by jstkdng** [comment]
pretty much, I've exhausted the possible causes of any slowdowns related to my socket implementation. Unless there's something I'm not taking into account, it could just be that slow pcs are slow.

**Comment by jstkdng** [comment]
hmm, well, you win some you lose some, keep using the fifo or don't. You are free to do what you want. Unless there's more informacion that can aid in solving this, closing.
