### ISSUE TITLE
bug: for wayland as output, image stays on top of everything

### ISSUE THREAD

**Issue by justchokingaround** [jstkdng/ueberzugpp#64]
In this example, I use groups for my windows, and the problem is that with the `wayland` image output method, the window stays on top, no matter what. There were also other cases where similar unwanted (for me) behavior happened, but I could not reproduce it yet. I am unsure whether I should report this here or maybe on the hyprland repo. I am also unsure whether this is within the scope of this project.

https://github.com/jstkdng/ueberzugpp/assets/44473782/8e7be88c-fa56-498c-994a-f091376bc10c

**Comment by jstkdng** [comment]
No, that is expected. The `wayland` output method is just a floating window. You can use kitty if your terminal and wrapper support it. You could use tmux instead of window groups

**Comment by justchokingaround** [comment]
The problem with tmux, is that it doesn't support sixel, sadly. Anyway I'll be closing this now
