### ISSUE TITLE
[ideas] for efficiency improvements

### ISSUE THREAD

**Issue by ghost** [jstkdng/ueberzugpp#65]
1. one way, would be to go from bash to sh. That's not much, but it's relatively simple.
2. an other way would be to use ?ffmpeg/libmpv? for decoding the images. mpv is a video player, but it's amazingly fast as an image viewer, it put real image viewers to shame. Even gifs are far more efficient on mpv, it's just weird seeing that. This way even normal videos could be supported.

(this has nothing to do with the slowness bug)

**Comment by jstkdng** [comment]
>This way even normal videos could be supported.

at some point `ueberzugpp` supported videos through opencv but I removed that functionality as it consumes a lot of your CPU. It used ffmpeg so there'd be no need to introduce new dependencies.

**Comment by jstkdng** [comment]
Yeah, mpv is fast as it uses opengl/vaapi for almost everything, meanwhile `ueberzugpp` is using the CPU except for resizing. Even if I used libmpv for video/gif decoding, displaying the data would be done without opengl. Adding opengl/vulkan support would require quite a lot of research, but would still be interesting.

**Comment by jstkdng** [comment]
Low level access is required for `ueberzugpp` to work. High level frameworks don't allow the stuff required by `ueberzugpp` to work.

>I understood that ueberzugpp is like a normal application, except that it follows around a specific window.

`ueberzugpp` uses low level APIs to create a window and attach it to another one. That would not be possible with high level frameworks such as GTK or Qt.

**Comment by jstkdng** [comment]
>ueberzugpp could be officially a compatibility layer so that projects only deal with one method

indeed, I even got into a fight with the guy that was implementing sixel support under ranger.

>ranger has 4 additional methods and an additional experimental one. And all of these are not complex low level stuff.

only X11 and wayland require low level stuff, the other methods are fairly easy to implement on vanilla python.

**Comment by jstkdng** [comment]
That'd only be possible on X11, and image vieweing is already pretty fast, it takes 15ms to load an image into `ueberzugpp` and I doubt it'd be any faster using libmpv. Now, gifs and videos could benefit from the hwaccel of libmpv, that'd need some more research.
