### ISSUE TITLE
libpoppler-glib.so.8 and libopenslide.so.0

### ISSUE THREAD

**Issue by 465788227** [jstkdng/ueberzugpp#67]
i successfully compiled ueberzug on manjaro,
but when i run it, it gives out these errors!
`unable to load "/usr/lib/vips-modules-8.14/vips-poppler.so" -- libpoppler-glib.so.8: cannot open shared object file: No such file or directory`

`(process:55262): VIPS-WARNING **: 11:14:11.063: unable to load "/usr/lib/vips-modules-8.14/vips-openslide.so" -- libopenslide.so.0: cannot open shared object file: No such file or directory`

**Comment by jstkdng** [comment]
Those errors can be safely ignored. If you want to remove them add the `--silent` flag or install `openslide` and `poppler-glib`

**Comment by 465788227** [comment]
> Those errors can be safely ignored. If you want to remove them add the `--silent` flag or install `openslide` and `poppler-glib`

thanks!
i installed `openslide` n `poppler-glib` but only openslide error has disappeared.
besides, it gives this error at the end
`memory: high-water mark 0 bytes`

i actually use old ueberzug!
i just wanna try if your ueberzugpp can be faster than it or not,
but i'm being stuck at the above error!

**Comment by jstkdng** [comment]
Try installing `libvips-git` from the aur. That should fix the issues.

>just wanna try if your ueberzugpp can be faster than it or not,

`ueberzugpp` is faster than `ueberzug`

**Comment by 465788227** [comment]
> Try installing `libvips-git` from the aur. That should fix the issues.
> 
something wrong with libpoppler-glib.so.8 that is beyond my capabilities!

**Comment by jstkdng** [comment]
Could be an issue with manjaro

**Comment by jstkdng** [comment]
No response from OP for some time know, closing.
