### ISSUE TITLE
support for 16-bit color depth

### ISSUE THREAD

**Issue by basaran** [jstkdng/ueberzugpp#72]
Hello,

Would it be possible to include support for X11 running in 16-bit color depth. Majority of the display panels available today are actually 8BIT+FRC and temporal dithering to make up for the rest of the palette. It basically flickers the pixels to imitate colors, which could cause eye strain on some (as in me).

I run my X11 in 16-bit for that reason, and ueberzugpp is displaying images like below for me:

![image](https://github.com/jstkdng/ueberzugpp/assets/30809170/d19530ad-8848-4c29-a0e0-33a97ca48d86)

This was taken on the latest git built, running inside alacritty - tmux, ranger. I confirmed images display fine if I switch over to 24-bit color depth. Here's my X11 config.

```
Section "Screen"
   Identifier   "Default Screen"
   Monitor      "Configured Monitor"
   Device       "Intel Graphics"
   DefaultDepth 16 #set the color depth to 16-bit
   SubSection "Display"
      Depth 16
      Modes "1920x1080"
   EndSubSection
EndSection
```

**Comment by jstkdng** [comment]
Hi, it should be possible but some research would be required. And i'm not sure if it would work on the other display methods. Probably only X11 and sixel. Would you be able to test sixel and see how it looks?

**Comment by basaran** [comment]
Hello,

> Would you be able to test sixel and see how it looks?

Yes, of course. Thank you for looking into this.

**Comment by jstkdng** [comment]
hmm, I gave it a try but couldn't do it, sixel does work though, so I'd suggest you use that.

**Comment by xlucn** [comment]
Does this also apply for cases where only the images are in 16-bit color depth?

I run into some cases where png files with 16-bit color depth are generated by `convert` command (see https://github.com/xlucn/fontpreview-ueberzug/issues/22 for example) or screenshots from MPV. I am running WM in 8-bit color depth, yet ueberzugpp still renders the images wrong.

**Comment by jstkdng** [comment]
>Does this also apply for cases where only the images are in 16-bit color depth

not necessarily, they could be supported but some explicit support has to be added (for opencv). Can you test using libvips and see if it works?

> I am running WM in 8-bit color depth

is that a typo?

**Comment by xlucn** [comment]
> > Does this also apply for cases where only the images are in 16-bit color depth
> 
> not necessarily, they could be supported but some explicit support has to be added (for opencv). Can you test using libvips and see if it works?

Thanks for the reply, I have tried with `--no-opencv` option and confirm it works for those cases!

> > I am running WM in 8-bit color depth
> 
> is that a typo?

I meant I tested in a window manager in normal 8-bit color depth.

**Comment by jstkdng** [comment]
>I meant I tested in a window manager in normal 8-bit color depth.

ah, I thought you were running x11 in 255 colors or smth

can you upload one of the images generated from the font preview? Adding support from opencv should be simple

**Comment by xlucn** [comment]
Here is an example image

![fontpreview-ueberzug-img](https://github.com/jstkdng/ueberzugpp/assets/12032219/767a0b21-ba85-4c2c-8dfa-7020b7348997)

**Comment by jstkdng** [comment]
16 bit images should be working with opencv now on master, I do wonder why you save in that format though

**Comment by xlucn** [comment]
> 16 bit images should be working with opencv now on master, I do wonder why you save in that format though

Thanks, I will try that when I got the time.

As for the format, it's not my intention at all. Both imagemagick command and MPV screenshot just somehow generated those images and I have no idea why :confused:
