### ISSUE TITLE
Incorrect brew folder format

### ISSUE THREAD

**Issue by jeronimobarea** [jstkdng/ueberzugpp#76]
Hi, the current brew format does not allow to run a `brew tap` on it, according to the `hombrew` docs it should be `hombrew-{something}` to be valid.

https://docs.brew.sh/Taps#repository-naming-conventions-and-assumptions

**Comment by jstkdng** [comment]
nice, didn't know about taps. I've created another repo for easier tapping. `brew install jstkdng/ueberzugpp/ueberzugpp` should work until I can get this into brew/core
