### ISSUE TITLE
Questions about transparency/alpha

### ISSUE THREAD

**Issue by yamibyte** [jstkdng/ueberzugpp#8]
First off, let me thank you for this tool. I wish you luck with the future development of it.

I have two questions, both regarding transparency. I am using st terminal with alpha patch installed (picom dependent).

1. Is there a way to prevent ueberzug++ from painting black parts of the terminal that are not used for rendering of the image?

2. Is it possible and if so then do you plan to add support for transparent images, e.g. PNG with alpha channel?

![image](https://user-images.githubusercontent.com/91797732/219899650-87197330-85a2-4f9d-ba19-2b16ea52f645.png)

The Tux image I've used could be found [here](https://upload.wikimedia.org/wikipedia/commons/a/af/Tux.png).

**Comment by jstkdng** [comment]
>transparent images

X11 supports alpha channel but it does nothing with it, sixel doesn't support alpha channel.

>painting black parts of the terminal

Yeah that can be done, I just have to improve the image resizing algorithm I'm using. It seems that tux image didn't get resized to fit in the constraints you gave it.

**Comment by yamibyte** [comment]
@jstkdng Thank you, the black parts are gone now, and the image is scaled properly now.

![image](https://user-images.githubusercontent.com/91797732/219935074-0e16367a-4c51-4c8d-8811-7de687f6c657.png)

> sixel doesn't support alpha channel

Got it.
