### ISSUE TITLE
Failed to build with libressl

### ISSUE THREAD

**Issue by fabioesantos** [jstkdng/ueberzugpp#80]
The project use the call "EVP_blake2b512" not implemented in libressl.
There is some "EVP_blake2b512" replacement compatible with libressl?

**Comment by jstkdng** [comment]
hi, thanks for reporting. What distro and which version of libressl does it have?

**Comment by fabioesantos** [comment]
Hi, I use gentoo with the musl libc and libressl-3.8.0

**Comment by jstkdng** [comment]
Ok. I added some changes to the master branch that could fix the issue. Test it out.

**Comment by fabioesantos** [comment]
After the last commit the program build perfectly with libressl, thank you!

**Comment by jstkdng** [comment]
alright, closing then.
