### ISSUE TITLE
Image preview in ranger produces low-quality image on Mac

### ISSUE THREAD

**Issue by BigBrotherJu** [jstkdng/ueberzugpp#81]
I'm using ranger in kitty on Mac. kitty and ranger are the latest, and I have set `set preview_images_method ueberzug` in ranger's config. But ranger produces low-quality image preview. Seems like chafa is used as the output method.

<img width="794" alt="image" src="https://github.com/jstkdng/ueberzugpp/assets/47515692/02c57934-a6f8-4d5f-acca-25257ac9e2ff">

Is there any way to enable other output methods like kitty?

**Comment by jstkdng** [comment]
Hello, you can create a config file under `$HOME/.config/ueberzugpp/config.json` and change the output type there. For kitty write this.
```json
{
    "layer": {
        "output": "kitty"
    }
}
```

**Comment by BigBrotherJu** [comment]
Thanks! Worked like a charm.
