### ISSUE TITLE
[BUG] memory: high-water mark 0 bytes

### ISSUE THREAD

**Issue by Beethoven-n** [jstkdng/ueberzugpp#83]
so i have been testing this in non-ranger environments, and found this bug.

here's my test command.
`ueberzug layer <<< '{"action":"add","height":49,"identifier":"preview","path":"/home/dogbold/pictures/vrchat/VRChat_2023-06-30_00-05-52.471_1920x1080.png","scaler":"contain","width":100,"x":0,"y":0}'`

when i run that command, or use ueberzug in literally any form that isn't ranger, i get this error:
`memory: high-water mark 0 bytes`

if i run it with --no-opencv i get this error instead:
`memory: high-water mark 13.77 MB`
`error buffer: vips_image_get: field "n-pages" not found`

there some kinda log i can give you to get more info to you?

**Comment by jstkdng** [comment]
hey, tha's not really a bug, just debug output from libvips. You can hide it with the `--silent` flag. To remove it for good you have to install a version of libvips compiled in release mode. What distro are you using?

**Comment by Beethoven-n** [comment]
oh, i thought that was the error.
it doesn't actually present an image after that error pops up.
i'm on arch

**Comment by Beethoven-n** [comment]
on a lark, i went through journalctl, and aha! a stack trace
please don't require an out of date version of glibc
```
systemd-coredump[195937]: [🡕] Process 195935 (ueberzug) of user 1000 dumped core.

                                      Stack trace of thread 195935:
                                      #0  0x00007f74f469f26c n/a (libc.so.6 + 0x8926c)
                                      #1  0x00007f74f464fa08 raise (libc.so.6 + 0x39a08)
                                      #2  0x00007f74f4638538 abort (libc.so.6 + 0x22538)
                                      #3  0x00007f74f489ca6f _ZN9__gnu_cxx27__verbose_terminate_handlerEv (libstdc++.so.6 + 0x9ca6f)
                                      #4  0x00007f74f48b011c _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xb011c)
                                      #5  0x00007f74f48b0189 _ZSt9terminatev (libstdc++.so.6 + 0xb0189)
                                      #6  0x00007f74f48b03ed __cxa_throw (libstdc++.so.6 + 0xb03ed)
                                      #7  0x00007f74f48a016d _ZSt24__throw_invalid_argumentPKc (libstdc++.so.6 + 0xa016d)
                                      #8  0x000056087a3404b3 n/a (ueberzug + 0x574b3)
                                      #9  0x000056087a39bfbf n/a (ueberzug + 0xb2fbf)
                                      #10 0x000056087a302f25 n/a (ueberzug + 0x19f25)
                                      #11 0x00007f74f4639850 n/a (libc.so.6 + 0x23850)
                                      #12 0x00007f74f463990a __libc_start_main (libc.so.6 + 0x2390a)
                                      #13 0x000056087a3035a5 n/a (ueberzug + 0x1a5a5)
                                      ELF object binary architecture: AMD x86-64
```

**Comment by jstkdng** [comment]
So it works inside ranger but outside it doesn't? 

>i really hope ueberzugpp doesn't require an out of date version of glibc

it doesn't need a particular version of glibc

for the stacktrace to be useful you need to have the debug symbols. Did you install `ueberzugpp` from the AUR? a `-debug` package should exist for you to install.

**Comment by Beethoven-n** [comment]
there isn't a -debug package on the AUR, only [this one](https://aur.archlinux.org/packages/ueberzugpp). looking at /tmp/ueberzugpp-$USER.log, i do see that it does everything normally, but then immediately exits. am i supposed to be throwing this in a loop, even in shell?

**Comment by jstkdng** [comment]
>there isn't a -debug package on the AUR

there should be a -debug package where your aur helper built `ueberzugpp`

>clearly the issue is that i just don't know how to use this program

ah, I see. `ueberzugpp` is not a one-off command, it has to stay running in the background.

**Comment by Beethoven-n** [comment]
that's the thing! for some reason, it even exits when you do this, it just immediately exits. does it not loop on its own when put in the background?
`mkfifo fifo; ueberzug < fifo &`
`echo '{"action":"add","height":49,"identifier":"preview","path":"/home/dogbold/pictures/vrchat/VRChat_2023-06-30_00-05-52.471_1920x1080.png","scaler":"contain","width":100,"x":0,"y":0}' > fifo`

**Comment by jstkdng** [comment]
no, it continues to run in the background. You can check the `scripts/` folder in this repo for some examples.
