### ISSUE TITLE
Support for debian arm?

### ISSUE THREAD

**Issue by asdfghjkl403622** [jstkdng/ueberzugpp#88]
Hello!

I am writing this from my pinephone pro, and it doesn't seem like there is any easy way to install this project on debian arm, as some dependencies like tbb are not available in the repos. is there a possibility of adding a ppa or .deb for arm based debian distros?

**Comment by jstkdng** [comment]
hello. Doesn't the pinephone pro run some form of gnome with wayland? Or can it run under X11.

**Comment by asdfghjkl403622** [comment]
I have not heard of anyone getting any success out of X11 outside of sxmo iirc, so Wayland on either Phosh, KDE mobile, or swmo all work. so yes, it would have to be wayland supported, which this project seems to support wayland.

**Comment by jstkdng** [comment]
>which this project seems to support wayland.

it does but not all compositors are created equal, (proper) support for kde is still under research and for gnome I don't think it's even possible.

`ueberzugpp` could work under XWayland, does XWayland work in any of those?

**Comment by asdfghjkl403622** [comment]
yeah, xwayland does work

**Comment by jstkdng** [comment]
alright, then, the easiest way to build on debian would be to clone from master and run `debuild` from the project root.

**Comment by asdfghjkl403622** [comment]
ok, lemme try that

**Comment by asdfghjkl403622** [comment]
`gmake[3]: Leaving directory '/home/mobian/ueberzugpp/obj-aarch64-linux-gnu/CMakeFiles/CMakeScratch/TryCompile-TvWNpb'
gmake[2]: Leaving directory '/home/mobian/ueberzugpp/obj-aarch64-linux-gnu/CMakeFiles/CMakeScratch/TryCompile-TvWNpb'


Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}


dh_auto_configure: error: cd obj-aarch64-linux-gnu && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DFETCHCONTENT_FULLY_DISCONNECTED=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib/aarch64-linux-gnu -DENABLE_WAYLAND=ON -DFETCHCONTENT_FULLY_DISCONNECTED=ON .. returned exit code 1
make[1]: *** [debian/rules:8: override_dh_auto_configure] Error 2
make[1]: Leaving directory '/home/mobian/ueberzugpp'
make: *** [debian/rules:5: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui failed`

**Comment by jstkdng** [comment]
hm, do you have `build-essentials` installed?

**Comment by asdfghjkl403622** [comment]
build essential is installed

**Comment by asdfghjkl403622** [comment]
[output.txt](https://github.com/jstkdng/ueberzugpp/files/12032655/output.txt)

**Comment by jstkdng** [comment]
Now that's a completely different error than the previous one, at least it is easier to fix.
Go to the root of the project and run this `git submodule update --init`, after that `debuild` should work.

**Comment by asdfghjkl403622** [comment]
`dpkg-deb: building package 'ueberzugpp-dbgsym' in '../ueberzugpp-dbgsym_2.8.6_arm64.deb'.
dpkg-deb: building package 'ueberzugpp' in '../ueberzugpp_2.8.6_arm64.deb'.
 dpkg-genbuildinfo -O../ueberzugpp_2.8.6_arm64.buildinfo
 dpkg-genchanges -O../ueberzugpp_2.8.6_arm64.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source --after-build .
dpkg-buildpackage: info: full upload; Debian-native package (full source is included)
Now running lintian ueberzugpp_2.8.6_arm64.changes ...
Finished running lintian.
Now signing changes and any dsc files...
 signfile dsc ueberzugpp_2.8.6.dsc JustKidding <jk@vin.ovh>
gpg: directory '/home/mobian/.gnupg' created
gpg: keybox '/home/mobian/.gnupg/pubring.kbx' created
gpg: skipped "JustKidding <jk@vin.ovh>": No secret key
gpg: /tmp/debsign.cNrwvllk/ueberzugpp_2.8.6.dsc: clear-sign failed: No secret key
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1112:
running debsign failed`

**Comment by jstkdng** [comment]
The build was succesful and there should be a .deb file located in the directory above the ueberzugpp source directory. Just run `sudo apt install ./ueberzugpp_2.8.6_arm64.deb`.

**Comment by asdfghjkl403622** [comment]
it installed without an issue, but when I run ytfzf with just the -t option it doesn't work, and when I try to specify ueberzugpp using -T it says that it's not a valid thumb viewer. It just keeps infinitely loading whenever I highlight a video in ytfzf

**Comment by jstkdng** [comment]
yeah, `ueberzugpp` is not a valid thumb viewer. Check their docs for the available ones.
If you want to use xwayland you have to create a file with the path `$HOME/.config/ueberzugpp/config.json` containing the following content.

```
{
    "layer": {
        "output": "x11"
    }
}
```

and run `ytfzf` this way. `ytfzf -t -T ueberzug`

**Comment by asdfghjkl403622** [comment]
hey! sorry for making you walk me through this, but that didn't work, and I'm still getting the same issue. is there a thumb viewer you would recommend then? as there are multiple that require this project to work

**Comment by jstkdng** [comment]
I'd say give kitty a try.

**Comment by asdfghjkl403622** [comment]
kitty does not support my opengl versions sadly, just tried it and checked github issues :(

**Comment by jstkdng** [comment]
foot could work with the sixel backend

**Comment by jstkdng** [comment]
no response from OP for some time now, closing

**Comment by Kabouik** [comment]
I am happy to report that I was able to build `ueberzugpp` on Droidian (Trixie) on a aarch64 phone using:

```
sudo apt install libtbb-dev xcb-util-image libvips-dev libsixel-dev libchafa-dev # libvips-dev was a big one with many dependencies
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_WAYLAND=ON -DENABLE_X11=OFF -DENABLE_OPENCV=OFF ..
cmake --build .
```

Would be great if aarch64/arm binaries were available in the apt repository for automated updates. or as pre-build binaries at the download link supplied in the README.

Thanks for making `ueberzugpp`!

**Comment by jstkdng** [comment]
>I am happy to report that I was able to build ueberzugpp on Droidian (Trixie) on a aarch64 phone

awesome

>Would be great if aarch64/arm binaries were available in the apt repository for automated updates.

I just noticed aarch64 is supported on the current repository provider, I'll check if it works without issues.

>Thanks for making ueberzugpp!

glad you like the proyect, don't forget to give it a star

**Comment by jstkdng** [comment]
Builds correctly on aarch64 and ppc64le. It does come with all the dependencies, like opencv, so it is pretty big.

**Comment by Kabouik** [comment]
Awesome news! I already had starred the project. Now I can only hope for a Guix package for `ueberzugpp` one day, but I can't spend time on it right now (and I'm a noob with Guix packaging so I would need a lot of time).

**Comment by jstkdng** [comment]
I tried creating a guix package but couldn't do it. Seems their libvips packaging is broken.

**Comment by Kabouik** [comment]
Damn. As a temporary workaround, and since you already have pipelines in place for prebuilt binaries in most architectures, a Guix package on the nonguix channel would allow packaging prebuilt binaries and therefore not bothering with libvips. For a sources-based distributions, and for visibility, a proper sources-based Guix package would be best of course, but I'm sure many Wayland Guix users would be happy with having prebuilt ueberzugpp managed by their favourite package manager.

As for the failed attempt, did you report it on the tracker or on Libera #guix? They're usually very active and helpful there.

**Comment by jstkdng** [comment]
>As for the failed attempt, did you report it on the tracker or on Libera #guix? They're usually very active and helpful there.

not really, I no longer use guix so I didn't want to spend a lot of time testing and reporting stuff. Once it broke I lost interest.
