### ISSUE TITLE
[bug] zsh: IOT instruction (core dumped)

### ISSUE THREAD

**Issue by justchokingaround** [jstkdng/ueberzugpp#89]
I get this error whenever I try to run `ueberzugpp layer` or any script that invokes ueberzugpp. I've also tried rolling back and building from source for older commits, but encountered the same issue. My guess is that it's probably a hyprland or wayland bug, but since I'm not exactly sure, I wanted to know if you might know what causes this?

![image](https://github.com/jstkdng/ueberzugpp/assets/44473782/9ace96c2-d569-4656-89cc-7f4ab0b92684)

```
 _    _      _                                           
| |  | |    | |                                _     _   
| |  | | ___| |__   ___ _ __ _____   _  __ _ _| |_ _| |_ 
| |  | |/ _ \ '_ \ / _ \ '__|_  / | | |/ _` |_   _|_   _|
| |__| |  __/ |_) |  __/ |   / /| |_| | (_| | |_|   |_|  
 \____/ \___|_.__/ \___|_|  /___|\__,_|\__, |            
                                        __/ |            
                                       |___/     v2.8.8
[2023-07-13 03:07:51.607] [terminal] [info] TERM="xterm-256color", TERM_PROGRAM="WezTerm"
[2023-07-13 03:07:51.607] [wayland] [info] Using hyprland socket /tmp/hypr/5e577acf516b80173f695a458c2cc188a4d64560_1689210057/.socket.sock
```

**Comment by jstkdng** [comment]
could be, I think hyprland just recently got an upgrade on arch and they probably changed their json api.

**Comment by jstkdng** [comment]
hey, I just tested latest hyprland and it's working. Can you try compiling from master and check if it works?

**Comment by justchokingaround** [comment]
so this is what happens for me on the latest `ueberzugpp` version, compiled from source with the wayland flag:

- without any config:
first image is displayed, on my 2nd monitor, then every other picture is not
![image](https://github.com/justchokingaround/lobster/assets/44473782/5258d8be-6db2-48a6-9209-6e8a86fcbfa9)

- setting sixel as the output in the config:
everything seems to be working as expected, no problems encountered yet
![image](https://github.com/justchokingaround/lobster/assets/44473782/42cba633-ff0a-41c2-8a33-5bacfa25d5e2)

**Comment by jstkdng** [comment]
I see, I've made some changes, check if it works fine.

**Comment by justchokingaround** [comment]
the image appears for a very short amount of time, and then disappears, and the next ones don't show up at all. the log isn't very useful so i didn't attach it

**Comment by jstkdng** [comment]
hm, that means `ueberzugpp` is crashing now. please try to run `ueberzugpp` and then run `coredumpctl -1 debug` and then `bt` once you have a prompt. Post the results from that.

**Comment by justchokingaround** [comment]
the original error happens again, on the latest main branch commit, it's just happening on a different line this time:
![image](https://github.com/jstkdng/ueberzugpp/assets/44473782/aa6af84e-236a-40a0-ac11-9e81b3cbcbd6)

**Comment by jstkdng** [comment]
alright, I think I understand the problem, maybe the issue is related to the number of windows you have opened.

**Comment by jstkdng** [comment]
I uploaded some changes, should be working (?, works fine on my end.

**Comment by justchokingaround** [comment]
![image](https://github.com/jstkdng/ueberzugpp/assets/44473782/dec3d71b-31ce-47f2-8615-c7885c4df702)

so it does work, however the positioning is wrong, for every application i tried it with

for reference, this is the correct positioning, that used to exist in the past:
![image](https://github.com/jstkdng/ueberzugpp/assets/44473782/485ffe85-018d-49cc-981b-90241162785c)

**Comment by jstkdng** [comment]
you really like lain huh? anyway, uploaded some more changes, should hopefuly work unless there's some more weird multimonitor issues with hyprland

**Comment by justchokingaround** [comment]
the position is perfect, except the fact that it appears in the correct spot, but on the wrong monitor

(let's all love lain)

**Comment by jstkdng** [comment]
Ok... maybe this will work, if it doesn't I'm gonna need to get a second monitor. Can you post the output of `hyprctl clients -j` and `hyprctl monitors -j` ?

**Comment by justchokingaround** [comment]
it did work! with wayland output:
![image](https://github.com/jstkdng/ueberzugpp/assets/44473782/7a8f100d-7fdb-41bb-9437-0ec747fdf2a6)

**Comment by justchokingaround** [comment]
(fzf and lf also work fine)

**Comment by jstkdng** [comment]
can you test if sway also works?

**Comment by justchokingaround** [comment]
yep, ill test it in a bit

**Comment by justchokingaround** [comment]
it seems to force sixel output, but that works

**Comment by jstkdng** [comment]
what? uhh, that's weird. Unless you forgot to clear the environment variables from hyprland or smth.

**Comment by justchokingaround** [comment]
that was directly after rebooting, and i made sure my config specified wayland for the output. after switching to hyprland, everything worked as intended

**Comment by jstkdng** [comment]
that is weird, maybe somehow the $SWAYSOCK variable is not reaching `ueberzugpp`. Oh well, not much I can do there.
