### ISSUE TITLE
Not work in vifm

### ISSUE THREAD

**Issue by dongdongbh** [jstkdng/ueberzugpp#9]
I following [vifmimg](https://github.com/thimc/vifmimg) setup ueberzug for vifm. remove `-p json` in https://github.com/thimc/vifmimg/blob/6e4c562c302405c27f0de7c5c1a335ce1a5765e2/vifmrun#L16
since -p json is not supported.

when I open a pdf file, their is a thumbnail picture created in cache directory, which proof the other part works fine, but it the image do not shows up in vifm, and the vifm stucked. When I open a image, their also no image shows up, and the vifm also stucked.

### Test environment
system: ubuntu server 20.04
terminal: alacritty
vifm: v0.12.1

**Comment by jstkdng** [comment]
hey, just checked out that project and it is using some syntax seebye introduced before it died.

Change this file

https://github.com/thimc/vifmimg/blob/master/vifmimg#L9

and replace width and height with max_width and max_height.

**Comment by dongdongbh** [comment]
Just changed to max_width and max_height, but it still do not show image and stuck the program

**Comment by jstkdng** [comment]
weird indeed, I'd recommend opening an issue in the vifmimg repository.

**Comment by dongdongbh** [comment]
I posted an issue in vifm, they said maybe it related to ueberzugpp command~

**Comment by dongdongbh** [comment]
I open an [issue](https://github.com/thimc/vifmimg/issues/47) in vifmimg. I temporarily changed to ranger, and it works fine with ueberzuggpp, thanks for your great work!

**Comment by xaizek** [comment]
As I've said, it's `ueberzugpp` fault. It just isn't that compatible with `ueberzug`. In addition to not accepting `height`, `width` and `layer -p`, it also requres `max_height`, `max_width`, `x` and `y` to be numbers, while `vifmimg` passes them as strings.

**Comment by jstkdng** [comment]
yeah, a PR should be made to pass regular numbers instead of strings. Adding more validations will slow down this program. If the owner of vifmimg doesn't respond I'll add them.

**Comment by xaizek** [comment]
I thought you'd want to change `ueberzugpp` to work without doing any changes to `vifmimg`, otherwise `This is a drop-in replacement for the now defunct ueberzug project.` in the README doesn't hold and should be removed to not mislead users (also the binary should be renamed).

**Comment by jstkdng** [comment]
It is still the intention to be a drop-in replacement, I just didn't know how many other programs use the syntax that was introduced before, I was basing all my testing on ranger after all.

**Comment by jstkdng** [comment]
@dongdongbh I've made some changes for vifm but it's still not working. Could you test the latest release? perhaps my vifm config is wrong

**Comment by dongdongbh** [comment]
I will test it next week and give feedback then

**Comment by xaizek** [comment]
> perhaps my vifm config is wrong

Either that, `vifmimg` isn't in the `$PATH` or you haven't started Vifm using `vifmrun`. On my side v2.2.1 works just fine with `vifmimg`. Kudos for enhancing compatibility and making it not quit on errors! I couldn't make it fail and abandon the pipe by supplying invalid input.

I've also tried to use it in Vifm via a Lua plugin. It was a nice surprise that WMs without EWMH are supported, don't know if original ueberzug was able to do this too at some point, it didn't last time I tried.

**Comment by dongdongbh** [comment]
It works fine in my vifm with  the last version, and yes, you should use `vifmrun` to make it work according 'vifmimg' docs. 

PS: I also tested it on [w3m](https://w3m.sourceforge.net/), it not work in w3m.

**Comment by jstkdng** [comment]
seems it doesn't even work with OG ueberzug. https://bbs.archlinux.org/viewtopic.php?id=269270

**Comment by dongdongbh** [comment]
I didn't test the OG ueberzug, just saw people talking about it may use in w3m. 

In addition, it not work inside ssh, does this is the expected result?

**Comment by jstkdng** [comment]
X11 forwarding would be required for that, and even then it might need some validation.
