### ISSUE TITLE
Wayland Sway Multi-Monitor Image Preview

### ISSUE THREAD

**Issue by muaaz-ahmad** [jstkdng/ueberzugpp#90]
Hi, I stumbled upon your repository yesterday while trying to find a way to have image previews in **lf** so first of all kudos to you for making this solution available.
However I found a small issue with image preview which I spent the last night figuring out and finally got a working solution, the issue was with the image preview being populated on the wrong monitor (I have a 2 monitor setup). In the `move_window()` using the `get_window_info()` function we are getting the x and y coordinates for the active window on active monitor and that is working fine, the problem was in the actual ipc command which was originally

```c++
void SwaySocket::move_window(const std::string_view appid, int xcoord, int ycoord)
{
    std::ignore = ipc_command(fmt::format(R"([app_id="{}"] move absolute position {} {})", appid, xcoord, ycoord));
}
```
in the above function we shouldn't use the absolute keyword as mentioned on this [manpage](https://man.archlinux.org/man/sway.5.en#:~:text=moving%20tiled%20containers.-,move,-%5Babsolute%5D%20position%20%3Cpos_x) for sway, the absolute keyword makes the position relative to all outputs. In this case the image was always populating on the first monitor regardless of if we open the file manager on monitor 1 or monitor 2. Secondly, the command was missing the `for_window` keyword which should be used before the **app_id** criteria for matching.

This is the updated function

```c++
void SwaySocket::move_window(const std::string_view appid, int xcoord, int ycoord)
{
    std::ignore = ipc_command(fmt::format(R"(for_window [app_id="{}"] move position {} {})", appid, xcoord, ycoord));
}
```

There are also a few other minor issues I saw e.g. image dimensions sometimes go out of the boundaries of the terminal which I will try to fix too. Let me know what you think :)

**Comment by jstkdng** [comment]
Hey, I think the `for_window` part was removed to have one-time commands than permanent rules, the issue was described in this #77 . Does just removing `absolute` fix the multi monitor issue?

**Comment by muaaz-ahmad** [comment]
Yes, you are right. We can drop the `for_window` part to avoid permanent rules and I have verified it works and yes removing the `absolute` keyword has fixed the positioning issues for me. I have tested with different terminal placements on both monitors. One thing I would like to mention here is that both my monitors have the same resolution i.e. 1920x1080 so I was thinking we should also test it with monitors having different resolutions, what do you think?

Also, I will try to look into the minor image resizing issues I found while testing, will share if I find something :)

**Comment by jstkdng** [comment]
>we should also test it with monitors having different resolutions, what do you think?

sure m8, go nuts with testing, I'll remove the absolute keyword.

**Comment by jstkdng** [comment]
well, managed to get myself another smaller monitor so it works fine with different resolution monitors. Closing for now.
