### ISSUE TITLE
telescope integration in nvim

### ISSUE THREAD

**Issue by justchokingaround** [jstkdng/ueberzugpp#91]
just curious as to whether you got ueberzugpp to work with the `dharmx/telescope-media.nvim` plugin for neovim, i was reading an issue in which you were involved some time earlier, can't remember where?

**Comment by jstkdng** [comment]
oh yeah, last time I tested it was working fine under X11, should also work fine with wayland. Kitty/sixel doesn't work with neovim.

**Comment by justchokingaround** [comment]
oh, so you just used the default config, with the `ueberzug` backend and `x11` as the ueberzugpp backend?

**Comment by jstkdng** [comment]
yeah, just a simple config.

```lua
local telescope = require("telescope")

telescope.setup({
  extensions = {
    media = {
      backend = "ueberzug", -- "none"|"ueberzug"|"viu"|"chafa"|"jp2a"|"catimg"
      backend_options = {
          ueberzug = { xmove = -1, ymove = -1 },
        }
    }
  }
})
telescope.load_extension("media")
```

**Comment by justchokingaround** [comment]
tysm, that worked, with the wayland output option :+1:
