### ISSUE TITLE
[bug] some images fail to render

### ISSUE THREAD

**Issue by justchokingaround** [jstkdng/ueberzugpp#97]
no matter which output method is chosen, some images fail to render, example:
![image](https://github.com/jstkdng/ueberzugpp/assets/44473782/fc7ccfd8-bd9d-4cbc-902c-8606ae2dfb15)

for reference, here is the original file:
![lain_red](https://github.com/jstkdng/ueberzugpp/assets/44473782/8ad476d8-8fc6-49c1-9fdb-0727d65172b6)

**Comment by jstkdng** [comment]
does it show correctly without opencv?

**Comment by justchokingaround** [comment]
no, it has the same behavior for `no-opencv: false` and `no-opencv: true`

**Comment by jstkdng** [comment]
works on my machine with X11 and sixel, I'll test on wayland later. Which terminal are you testing sixel with?

**Comment by justchokingaround** [comment]
wezterm, but the same happens in a patched alacritty and in foot

**Comment by jstkdng** [comment]
ok, justed on wayland and it works fine. Try deleting the cache, maybe the resized image didn't save correctly.

**Comment by justchokingaround** [comment]
nope, still happening, sometimes it shows this message:
![image](https://github.com/jstkdng/ueberzugpp/assets/44473782/7579e89c-d454-41a4-bc9d-3bde034c533a)

**Comment by jstkdng** [comment]
damn, an opencl error. I'd say delete the cache and disable opencv.

**Comment by justchokingaround** [comment]
disabling opencv and clearing the cache does make it work, however it is still annoying that the errors pop up on the screen, since they displace the rest of what's being displayed, for instance if you're using lf, it will misplace everything

here are some of the error messages i was able to capture, if that helps:

![image](https://github.com/jstkdng/ueberzugpp/assets/44473782/3b390cf0-52f8-4967-8d67-ae4f84c664f3)
![image](https://github.com/jstkdng/ueberzugpp/assets/44473782/0a3cc895-83f2-458c-957e-053ae69929ec)

**Comment by jstkdng** [comment]
yup, that's an issue with arch's libvips package, it is buidling a debug package. Install `libvips-git`, I had to modified so that it builds a release package, those messages should be gone with that.

**Comment by justchokingaround** [comment]
yep, works nicely now, thank you yet again!
