### ISSUE TITLE
Add support for wayfire

### ISSUE THREAD

**Issue by Beethoven-n** [jstkdng/ueberzugpp#98]
can we get a move for some broader support on wlroots as a whole, rather than sticking to individual compositors?

thanks! :heart:

**Comment by jstkdng** [comment]
hey, wayland as a whole is supported, the difference is that sway and hyprland provide an easy way to setup window rules since the wayland backend just displays floating windows. If other compositors have some way to do the same then support for them could be implemented.

**Comment by Beethoven-n** [comment]
would there be a way to do it for _all_ wlroots compositors, or is the ecosystem really that locked down atm?

**Comment by jstkdng** [comment]
I'd say a lot of wayland/wlroots accept commands through a unix socket, but the strings/syntax they expect is different for all of them.

**Comment by Beethoven-n** [comment]
hm
well, i do use wayfire, i might be able to at least help with that

**Comment by jstkdng** [comment]
alright, maybe it could work. Does `wayfire` have rules to float a window, move a window and disable focus for a window? Does wayfire have a utility to change rules on the fly such as `swaymsg` or `hyprctl` ?

**Comment by Beethoven-n** [comment]
wayfire doesn't do tiling by default so that's taken care of, but you can at least move a window around
problem is you can't disable focus via window rules, it looks like. might have to do that some other way

**Comment by jstkdng** [comment]
the focus has to be disabled otherwise you'll lose focus from the terminal every time a new window shows up. It does at least have IPC so talking with it is possible.

>might have to do that some other way

maybe a new plugin would be required, open an issue and see if they'd be willing to implement the steal focus prevention.

**Comment by Beethoven-n** [comment]
i'm not sure how to file that _appropriately,_ is the thing. 
"add this thing so i can do another thing!" "why not just make the thing yourself?" "because i'm wanting this project i don't contribute code towards to work"

**Comment by jstkdng** [comment]
I think you are worrying too much, worst they can do is say they won't do it and close the issue. At that point maybe switch to sway?

Other people have asked the same on other projects and they have succededed, like on this one, https://github.com/zellij-org/zellij/pull/2212

**Comment by Beethoven-n** [comment]
i don't wanna switch to a tiler, but you're right

**Comment by Beethoven-n** [comment]
someone asked a question you might wanna answer over here https://github.com/WayfireWM/wayfire/issues/1837#issuecomment-1656578254

**Comment by jstkdng** [comment]
Alright, wayfire support is done. You can install a plugin with improved performance here https://github.com/jstkdng/ueberzugpp/tree/master/plugins/wayfire, but it should work the same as the one developed by @ammen99

**Comment by Beethoven-n** [comment]
before i close the tab, how do i build this? it doesn't have a meson.build file so i know it's not `meson build; ninja -C build install`

**Comment by jstkdng** [comment]
Run these commands.
```
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
```

inside the `plugins/wayfire` directory, after that copy the resulting `libueberzugpp.so` to `/usr/lib/wayfire` and edit your config accordingly

**Comment by Beethoven-n** [comment]
perfect. thanks!
for posterity i did it with `sudo install -Dm755 ./libueberzug.so /usr/lib/wayfire/libueberzug.so`

**Comment by jstkdng** [comment]
as long as it works, the file is called `libueberzugpp.so` though, not `libueberzug.so`

**Comment by Beethoven-n** [comment]
thanks for the catch, i actually woulda run into a bug if i did that
