### ISSUE TITLE
Is there a way to cancel the tasks ahead?

### ISSUE THREAD

**Issue by sxyazi** [jstkdng/ueberzugpp#99]
Hi, I'm integrating Überzug++ with [yazi](https://github.com/sxyazi/yazi) -- it's a terminal file manager.

I've found that Überzug++ draws each command in turn, even though it will be overwritten later. This causes noticeable lag when the user is switching quickly between many images, as it creates a lot of unnecessary drawing.

Is there a way I can cancel the previous tasks or allow only the last task to be drawn? The easiest way I can think of by far is to kill the previous process and create a new one each time, but this will introduce additional performance overhead.

https://github.com/jstkdng/ueberzugpp/assets/17523360/d343f5a7-89db-4710-8740-a724b23b4c93

**Comment by jstkdng** [comment]
hey, there's no way to do that at the moment, `ueberzugpp` should be fast enough to keep up with multiple draw commands though. Also, I'd recommend to not use the `--use-escape-codes` if you are spawning `ueberzugpp` from `yazi` since it alters terminal state and that might mess up `yazi`.

**Comment by sxyazi** [comment]
Yeah, I found this problem too, does this mean that using Überzug++ in macOS, doesn't work properly in kitty, while it's spawned by another tui app?

I tried to use it like I did with kitty's graphic escape code, i.e. with inherited stdout, but found that it didn't work very well...

**Comment by jstkdng** [comment]
kitty works fine, you can force the output instead. `ueberzugpp layer -o kitty` or  `ueberzugpp layer -o iterm2`

**Comment by sxyazi** [comment]
Yes, I passed that parameter, but there is still unintended behavior -- I need to test it further.

---
Off-topic: Is it possible to use an already downscaled image without any image manipulation? That's because yazi pre-caches the thumbnails in the background like DE's file manager does -- even if the user hasn't looked at it yet. I think it would be faster if Überzug++ could just use the cached image without opencv and libvips processing.

**Comment by jstkdng** [comment]
Processing is only done if the available space is smaller than the image. You can trick `ueberzugpp` into not doing any processing by passing a really large `max_width` and `max_height`.

**Comment by sxyazi** [comment]
I am not getting the correct output when I try to pass a command using `stdin`, my terminal is kitty and I specify the `-o kitty` parameter, I got the following output:

```
\x1b[?1;1;0S
```

The minimum code:

```rust
let mut child = Command::new("ueberzugpp")
  .env("SPDLOG_LEVEL", "debug")
  .args(["layer", "--use-escape-codes", "-o", "kitty"])
  .stdin(Stdio::piped())
  .stdout(Stdio::piped())
  .spawn()?;

let mut stdout = child.stdout.take().unwrap();
tokio::spawn(async move {
  let buf = &mut [0; 1024];
  loop {
    let n = stdout.read(buf).await.unwrap();
    if n == 0 {
      break;
    }
    info!("buf: {}", String::from_utf8_lossy(&buf[..n]));
  }
});

let mut stdin = child.stdin.take().unwrap();
stdin.write_all(br#"{"action":"add","identifier":"preview","max_height":0,"max_width":0,"path":"/home/dev/1.jpeg","x":0,"y":0}
"#).await.ok();

sleep(Duration::from_secs(10000)).await;
```

Not sure what I got wrong. 🤔

**Comment by jstkdng** [comment]
don't use the flag `--use-escape-codes`, that doesn't work when you spawn `ueberzugpp` from `yazi`

**Comment by sxyazi** [comment]
Thanks, kitty works now.

**Comment by jstkdng** [comment]
alright then, closing
